import assert from 'node:assert/strict';
import {targetFromRoute,createWorkbench,workbenchMarkup} from '../static/workbench.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names=[];async function check(name,fn){await fn();names.push(name)}
const target={kind:'trial',target:'joint:123:compare',label:'MP-261009-001 · 两种派序对照',state:'ready',note:'打开读取当前资料',version:1,route:'joint-schedule',params:{study:'MP-261009-001',view:'compare'}};
const entry={...target,id:'ENTRY',alias:'早会',section:'计划',is_home:false};
const board=(rows=[])=>({revision:3,home_mode:'overview',rows,limit:100,notice:'SIM'});
await check('four families preserve explicit original study and selected strategy',()=>{for(const route of ['finite-schedule','crew-schedule','joint-schedule','order-baselines'])assert.deepEqual(targetFromRoute('#'+route+'?study=000019&policy=priority'),{kind:'trial',lookup:{route,study:'000019',policy:'priority',view:''}})});
await check('comparison and frozen BOM views remain different destinations',()=>{assert.equal(targetFromRoute('#joint-schedule?study=MP1&view=compare').lookup.view,'compare');assert.deepEqual(targetFromRoute('#order-baselines?study=OB1&view=trial&policy=priority').lookup,{route:'order-baselines',study:'OB1',policy:'priority',view:'trial'})});
await check('temporary receipts are discarded without copying local filters',()=>{const d=targetFromRoute('#joint-schedule?study=MP1&receipt=SECRET&policy=due');assert(!JSON.stringify(d).includes('SECRET'));assert(!('receipt' in d.lookup));assert.equal(targetFromRoute('#joint-schedule?study=MP1&job=J1'),null)});
await check('duplicate, invalid modes and control characters are rejected',()=>{for(const url of ['#joint-schedule?study=A&study=B','#joint-schedule?study=A&policy=due&policy=priority','#crew-schedule?study=A&view=compare','#finite-schedule?study=A&view=trial','#joint-schedule?study=A&policy=bad','#joint-schedule?study=','#joint-schedule?study=A%0A'])assert.equal(targetFromRoute(url),null)});
await check('encoded identifiers preserve original text and generic module bookmarks stay generic',()=>{assert.equal(targetFromRoute('#joint-schedule?study=%E6%A8%A1%E6%8B%9F%2F00019').lookup.study,'模拟/00019');assert.deepEqual(targetFromRoute('#joint-schedule'),{kind:'module',target:'joint-schedule'})});
await check('saved cards expose family and unavailable states with escaping',()=>{const html=workbenchMarkup(board([{...entry,label:'<img>',state:'unavailable'}]),esc);assert(html.includes('试排与基线方案'));assert(html.includes('&lt;img&gt;'));assert(html.includes('disabled'))});
const pending=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};
function harness(intercept){
 const nodes=new Map(),events=new Map(),requests=[],navigations=[];let current=true,revision=0;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',disabled:false,open:false,close(){this.open=false}});return nodes.get(id)};
 const openButton={dataset:{deskOpen:'ENTRY'},addEventListener:(event,fn)=>events.set('open',fn)};
 const api=(path,options)=>{requests.push({path,options});const value=intercept?.(path,options);if(value!==undefined)return Promise.resolve(value);if(path==='workbench/trial-target')return Promise.resolve(target);if(path==='workbench/catalog')return Promise.resolve({rows:[target],page:1,size:25,total:1});if(path==='workbench/open')return Promise.resolve(target);return Promise.resolve(board())};
 const h={api,esc,header:(...v)=>v.join(''),modal:()=>{revision++;node('#detail').open=true},toast:()=>{},go:(route,params)=>navigations.push({route,params}),$:node,$$:s=>s==='[data-desk-open]'?[openButton]:[],on:(id,event,fn)=>events.set(id+':'+event,fn),isCurrent:()=>current,getModalRevision:()=>revision,refreshModels:()=>{throw Error('Trial must not load models')},applyModels:()=>{throw Error('Trial must not apply models')}};
 return {h,node,requests,events,navigations,leave:()=>current=false,replace:()=>revision++,fire:(id,event='click',e={})=>events.get(id+':'+event)(e)};
}
await check('quick favorite resolves typed target before exact catalog selection',async()=>{const x=harness();await createWorkbench(x.h).quickAdd('#joint-schedule?study=MP-261009-001&view=compare&receipt=SECRET',1);assert.deepEqual(x.requests[1],{path:'workbench/trial-target',options:{method:'POST',body:{route:'joint-schedule',study:'MP-261009-001',policy:'due',view:'compare'}}});assert.deepEqual(x.requests[2].options.body,{kind:'trial',q:target.target,page:1});assert.equal(x.node('#desk-add-save').disabled,false);assert(x.node('#desk-choice').textContent.includes('两种派序对照'))});
await check('existing exact destination opens organizer instead of creating duplicate',async()=>{const x=harness(path=>path==='workbench'?board([entry]):undefined);await createWorkbench(x.h).quickAdd('#joint-schedule?study=MP-261009-001&view=compare',1);assert(!x.requests.some(r=>r.path==='workbench/catalog'));assert(x.events.has('#desk-remove:click'))});
await check('leaving while resolving suppresses old picker',async()=>{const p=pending(),x=harness(path=>path==='workbench/trial-target'?p.promise:undefined);const job=createWorkbench(x.h).quickAdd('#joint-schedule?study=A&view=compare',1);await new Promise(r=>setImmediate(r));x.leave();p.resolve(target);await job;assert(!x.node('#detail').open);assert(!x.requests.some(r=>r.path==='workbench/catalog'))});
await check('replacing a modal while resolving suppresses stale response',async()=>{const p=pending(),x=harness(path=>path==='workbench/trial-target'?p.promise:undefined);const job=createWorkbench(x.h).quickAdd('#joint-schedule?study=A',1);await new Promise(r=>setImmediate(r));x.replace();p.resolve(target);await job;assert(!x.node('#detail').open)});
await check('newer quick favorite wins even if older lookup finishes later',async()=>{const old=pending(),x=harness((path,options)=>path==='workbench/trial-target'&&options.body.study==='OLD'?old.promise:undefined),w=createWorkbench(x.h);const a=w.quickAdd('#joint-schedule?study=OLD',1);await new Promise(r=>setImmediate(r));await w.quickAdd('#joint-schedule?study=NEW',1);old.resolve({...target,label:'STALE'});await a;assert(!x.node('#desk-choice').textContent.includes('STALE'));assert.equal(x.requests.filter(r=>r.path==='workbench/catalog').length,1)});
await check('open uses current server destination without model reload or cached receipts',async()=>{const x=harness(path=>path==='workbench'?board([entry]):undefined);await createWorkbench(x.h).render(null,1);await x.events.get('open')();assert.deepEqual(x.navigations,[{route:'joint-schedule',params:target.params}]);assert.deepEqual(x.requests.at(-1).options.body,{id:'ENTRY',revision:3})});
await check('failed lookup does not fall back to module or change configuration',async()=>{const x=harness(path=>path==='workbench/trial-target'?Promise.reject(Error('不可访问')):undefined);await assert.rejects(()=>createWorkbench(x.h).quickAdd('#joint-schedule?study=A',1),/不可访问/);assert(!x.node('#detail').open);assert(!x.requests.some(r=>r.options?.body?.action))});
console.log(JSON.stringify({success:true,checks:names.length,names,browser_acceptance:false}));
