// Pure HTML-string, source fixture and asynchronous state checks. No browser automation.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {setupSummary,setupDetails,setupEventRows,setupEventTable,setupTaskEvidence} from '../static/joint_setup.js';
import {createJointComparison} from '../static/joint_compare.js';
const fixtures=JSON.parse(fs.readFileSync(new URL('fixtures/setup_reading.json',import.meta.url)));
const d={...fixtures.mixed,receipt:'SIM',policy_receipts:{due:'D',priority:'P'},source_count:847},report=d.setup_reading;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(heads,rows)=>{assert(rows.every(r=>r.length===heads.length));return '<table>'+rows.map(r=>r.join('|')).join('\n')+'</table>'};
const panel=(title,actions,body)=>{assert.equal(typeof body,'string');return title+actions+body};
const h={esc,table,panel},names=[];async function check(name,fn){await fn();names.push(name)}
await check('imported mixed-product summary exposes preparation, finish and late-job tradeoff',()=>{const html=setupSummary(report,h);for(const value of ['360','240','-120','+6.6','+1','未排完批次'])assert(html.includes(value));assert(html.includes('不是')===false)});
await check('both preparation bars use one zero-based magnitude scale',()=>{const html=setupSummary(report,h);assert(html.includes('从0至 360'));assert(html.includes('width:66.66666666666666%'));assert.equal((html.match(/width:33.33333333333333%/g)||[]).length,3);assert.equal((html.match(/role="img"/g)||[]).length,2)});
await check('different scheduled identities cannot appear as preparation savings',()=>{const html=setupSummary(fixtures.partial,h);assert(html.includes('两列已排任务范围不同'));assert(html.includes('准备 <b>不可比较'));assert(html.includes('整案结束 <b>不可比较'));assert(html.includes('未全部排入'))});
await check('empty and paused states remain distinct from comparable zero',()=>{const empty=setupSummary(fixtures.empty,h),paused=setupSummary(fixtures.paused,h);assert(empty.includes('两列均未排入任务'));assert(empty.includes('已排 0 / 198'));assert(!empty.includes('NaN'));assert(paused.includes('未计算'));assert(!paused.includes('setup-bar-row'))});
await check('equal-scope zero preparation has zero width and exact zero difference',()=>{const r=structuredClone(report);for(const row of Object.values(r.columns))Object.assign(row,{initial_minutes:0,change_minutes:0,setup_minutes:0});Object.assign(r.summary,{chart_max_minutes:0,setup_delta_minutes:0});const html=setupSummary(r,h);assert(!html.includes('NaN'));assert(html.includes('准备 <b>0 分钟'));assert(html.includes('首次 10 次'))});
await check('default cross-family rows and combined filters preserve exact source identities',()=>{const a=setupEventRows(report);assert.equal(a.total,30);assert.equal(a.all,192);assert(a.rows.every(r=>r.kind==='change'));const r=report.resources[0].id,b=setupEventRows(report,{resource:r,policy:'priority',kind:''});assert(b.rows.every(x=>x.resource_id===r&&x.policy==='priority'))});
await check('pagination applies only to events and preserves complete source object',()=>{const before=structuredClone(report),a=setupEventRows(report,{kind:'',page:1}),b=setupEventRows(report,{kind:'',page:2});assert.equal(a.rows.length,30);assert.equal(b.rows.length,30);assert(!a.rows.some(x=>b.rows.includes(x)));assert.deepEqual(report,before)});
await check('event table exposes both original task and prior task identities',()=>{const rows=setupEventRows(report).rows,html=setupEventTable(rows,h);assert(html.includes(rows[0].option_id));assert(html.includes(rows[0].previous_task_id));assert(html.includes('跨族换型'));assert(html.includes('12 分钟'))});
await check('initial events and blocked detail do not invent a predecessor or zero event',()=>{const rows=setupEventRows(report,{kind:'initial'}).rows;assert(setupEventTable(rows,h).includes('初始族未登记'));const html=setupTaskEvidence({left:rows[0],right:null},h);assert(html.includes('未排入，无准备事件'));assert(html.includes('首次上机'))});
await check('all text identities are escaped without mutating source events',()=>{const r=structuredClone(report);r.events[0].family='<img src=x>';r.events[0].task_id='" onfocus="x';const before=structuredClone(r),html=setupEventTable([r.events[0]],h);assert(!html.includes('<img'));assert(!html.includes('data-setup-task="" onfocus='));assert.deepEqual(r,before)});
const pending=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};
function harness(intercept){
 const nodes=new Map(),events=new Map(),requests=[],modals=[];let active=true,revision=0;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',value:'',checked:true,textContent:'',disabled:false});return nodes.get(id)};
 const row=setupEventRows(report).rows[0],resource={dataset:{setupResource:row.resource_id},addEventListener:(name,fn)=>events.set('resource:'+name,fn)},mark={dataset:{setupTask:row.task_id},addEventListener:(name,fn)=>events.set('mark:'+name,fn)};
 const api=(path,options)=>{requests.push({path,options});const value=intercept?.(path,options);if(value!==undefined)return Promise.resolve(value);if(path==='joint-schedule')return Promise.resolve({rows:[d.study]});if(path.endsWith('/sources'))return Promise.resolve({rows:[],page:1,total:847,size:40});if(path.includes('/tasks/')){const id=decodeURIComponent(path.split('/tasks/')[1]);return Promise.resolve({task:d.tasks.find(t=>t.id===id),left:{demands:[],reservations:[]},right:{demands:[],reservations:[]},setup_reading:Object.fromEntries([['left','due'],['right','priority']].map(([s,p])=>[s,report.events.find(e=>e.task_id===id&&e.policy===p)||null])),notice:'SIM'})}return Promise.resolve(structuredClone(d))};
 return {node,events,requests,modals,mark,resource,leave:()=>active=false,fire:(id,event='click')=>events.get(id+':'+event)({}),h:{esc,table,panel,api,$:node,$$:s=>s==='[data-setup-resource]'?[resource]:s==='[data-setup-task]'?[mark]:[],on:(id,event,fn)=>events.set(id+':'+event,fn),header:(...v)=>v.join(''),modal:(...v)=>{revision++;modals.push(v)},toast:()=>{},go:()=>{},isCurrent:()=>active,getModalRevision:()=>revision}};
}
async function open(x){await createJointComparison(x.h).render(new URLSearchParams({study:d.study.id}),1);x.fire('#compare-setup-tab')}
await check('new view opens cross-family evidence without changing full summary',async()=>{const x=harness();await open(x);assert(x.node('#setup-page').textContent.includes('当前 30 / 两列全部 192'));assert(x.node('#main').innerHTML.includes('准备与交期取舍'));assert(x.node('#compare-body').innerHTML.includes('完整导出不变'))});
await check('resource drill intersects category and strategy, reset returns all events',async()=>{const x=harness();await open(x);x.fire('resource');assert.equal(x.node('#setup-resource').value,x.resource.dataset.setupResource);x.node('#setup-policy').value='priority';x.fire('#setup-policy','change');assert(x.node('#setup-events').innerHTML.includes('批次优先级优先'));x.fire('#setup-reset');assert.equal(x.node('#setup-kind').value,'');assert.equal(x.node('#setup-resource').value,'');assert(x.node('#setup-page').textContent.includes('当前 192'))});
await check('page and filters persist across tabs; reread resets to default',async()=>{const x=harness();await open(x);x.fire('#setup-reset');x.fire('#setup-next');assert(x.node('#setup-page').textContent.startsWith('2 /'));x.fire('#compare-task-tab');x.fire('#compare-setup-tab');assert(x.node('#setup-page').textContent.startsWith('2 /'));await x.fire('#compare-refresh');x.fire('#compare-setup-tab');assert.equal(x.node('#setup-kind').value,'change');assert(x.node('#setup-page').textContent.startsWith('1 /'))});
await check('task drill uses bound receipt and shows both original setup contexts',async()=>{const x=harness();await open(x);await x.fire('mark');assert.deepEqual(x.requests.at(-1).options.body,{receipt:'SIM'});assert(x.modals[0][1].includes('原设备换型依据'))});
await check('changing scope cancels pending task detail',async()=>{const p=pending(),x=harness(path=>path.includes('/tasks/')?p.promise:undefined);await open(x);const request=x.fire('mark');x.node('#setup-kind').value='initial';x.fire('#setup-kind','change');p.resolve({});await request;assert.equal(x.modals.length,0)});
await check('forged resource, task and filter values cannot escape selected evidence',async()=>{const x=harness();await open(x);x.resource.dataset.setupResource='INVALID';x.fire('resource');assert.equal(x.node('#setup-resource').value,'');x.mark.dataset.setupTask='INVALID';await x.fire('mark');assert(!x.requests.some(r=>r.path.includes('/tasks/')));const before=x.node('#setup-events').innerHTML;x.node('#setup-kind').value='INVALID';x.fire('#setup-kind','change');assert.equal(x.node('#setup-events').innerHTML,before)});
await check('local event filters do not narrow source pagination or full export',async()=>{const p=pending(),x=harness(path=>path.endsWith('/export')?p.promise:undefined);await open(x);x.fire('resource');await x.fire('#compare-sources');assert.deepEqual(x.requests.at(-1).options.body,{receipt:'SIM',page:1});const request=x.fire('#compare-json');assert.deepEqual(x.requests.at(-1).options.body,{receipt:'SIM',format:'json'});x.leave();p.resolve({});await request});
await check('no event match is a genuine empty detail while summary remains available',()=>{assert.equal(setupEventRows(report,{resource:'NONEXISTENT'}).total,0);assert(setupDetails(report,h).includes('查看各设备'));assert.equal(setupEventRows(fixtures.paused).all,0)});
console.log(JSON.stringify({success:true,checks:names.length,names,browser_acceptance:false}));
