// Pure functions and asynchronous state objects; no browser/DOM automation.
import assert from 'node:assert/strict';import fs from 'node:fs';
import {compareRows,policySummary,jobComparison,allocationRows,taskComparison,createJointComparison} from '../static/joint_compare.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),table=(headers,rows)=>{assert(rows.every(r=>r.length===headers.length));return JSON.stringify({headers,rows})},panel=(a,b,c)=>{assert.equal(typeof c,'string');return a+b+c};
const original=JSON.parse(fs.readFileSync(new URL('fixtures/joint_schedule_board_001_due.json',import.meta.url))),base=structuredClone(original);
const d={state:'compared',study:base.study,resource_study:base.resource_study,notice:'差值不是因果推断',policies:{due:'应完成时间优先',priority:'批次优先级优先'},columns:{due:{summary:base.summary,issues:[]},priority:{summary:base.summary,issues:[]}},receipt:'SYNTHETIC',policy_receipts:{due:'LEFT',priority:'RIGHT'},source_count:10,
 jobs:base.jobs.map(j=>({id:j.id,product_id:j.product_id,qty:j.qty,due:j.due,left:j,right:j,finish_delta_minutes:0,lateness_delta_minutes:0})),
 tasks:base.tasks.map(t=>({id:t.id,job_id:t.job_id,process:t.process,branch:t.branch,left:t,right:t,start_delta_minutes:0,finish_delta_minutes:0,changed:false})),
 materials:base.balances.map(b=>({material_id:b.material_id,material_name:b.material_name,unit:b.unit,left:b,right:b,reserved_delta_qty:'0',remaining_delta_qty:'0'})),
 allocations:base.reservations.map(a=>({demand_id:a.demand_id,supply_id:a.supply_id,unit:a.unit,left:a,right:a,qty_delta:'0',changed:false})),
 transitions:['scheduled','late','blocked'].flatMap(a=>['scheduled','late','blocked'].map(b=>({left:a,right:b,jobs:a===b?base.jobs.filter(j=>j.state===a).length:0,qty:a===b?base.jobs.filter(j=>j.state===a).reduce((v,j)=>v+j.qty,0):0}))),
 summary:{jobs:base.jobs.length,qty:50,tasks:198,both_complete:6,earlier:0,later:0,same:6,newly_complete:0,no_longer_complete:0,both_blocked:0,changed_tasks:0,changed_allocations:0}};
let checks=0;async function check(fn){await fn();checks++}
await check(()=>{const rows=Array.from({length:85},(_,i)=>({id:i,job_id:i<45?'A':'B',changed:i%2===0}));assert.equal(compareRows(rows,{job:'A'}).total,45);assert.equal(compareRows(rows,{job:'A',page:2}).rows.length,5);assert.equal(compareRows(rows,{changed:true}).total,43);assert.equal(compareRows(rows,{job:'missing'}).total,0)});
await check(()=>{const h=policySummary(d,{esc,table,panel});assert(h.includes('只计一次'));assert(h.includes('两列都排完'));assert(h.includes('未排入'));assert(!h.includes('最优策略'))});
await check(()=>{const paused=structuredClone(d);paused.summary=null;paused.columns.priority={summary:null,issues:['<script>']};const h=policySummary(paused,{esc,table,panel});assert(h.includes('差值均未计算'));assert(h.includes('&lt;script&gt;'));assert(!h.includes('两列都排完'))});
await check(()=>{const c=structuredClone(d);c.jobs[0].left.finished=null;c.jobs[0].finish_delta_minutes=null;c.jobs[0].lateness_delta_minutes=null;c.jobs[0].id='<img>';const h=jobComparison(c,{esc,table});assert(h.includes('不可比较'));assert(h.includes('&lt;img&gt;'));assert(!h.includes('<img>'))});
await check(()=>{const row={...d.allocations[0],left:null,qty_delta:'3'};const values=allocationRows([row],esc)[0];assert.equal(values.length,4);assert.equal(values[1],'0 · 无此笔预留');assert.equal(values[3],'3')});
await check(()=>{const task=d.tasks[0],detail={task,left:{demands:base.demands.filter(n=>task.left.demand_ids.includes(n.id)),reservations:base.reservations.filter(a=>task.left.demand_ids.includes(a.demand_id))},right:{demands:[],reservations:[]},notice:'<script>'};const h=taskComparison(detail,{esc,table});assert(h.includes('物料就绪等待分钟'));assert(h.includes('供给批次'));assert(!h.includes('<script>'))});
const pending=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve}};
const tick=()=>new Promise(r=>setImmediate(r));
function harness(api){const nodes=new Map(),events=new Map(),groups=new Map(),moves=[],modals=[];let active=true,revision=0;const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',value:'',checked:true,disabled:false});return nodes.get(id)};const h={api,esc,table,panel,header:(a,b,c)=>a+b+c,modal:(...v)=>{revision++;modals.push(v)},toast:()=>{},go:(...v)=>moves.push(v),$:node,$$:s=>groups.get(s)||[],on:(id,e,f)=>events.set(id+':'+e,f),isCurrent:()=>active,getModalRevision:()=>revision};return{h,node,events,groups,moves,modals,leave:()=>{active=false},replaceModal:()=>{revision++},fire:(id,event='click',value={})=>events.get(id+':'+event)(value)}}
const list={rows:[d.study]};const normal=path=>Promise.resolve(path==='joint-schedule'?list:structuredClone(d));
await check(async()=>{const x=harness(normal);await createJointComparison(x.h).render(new URLSearchParams({study:d.study.id}),1);assert(x.node('#main').innerHTML.includes('联立试排'));assert(x.node('#compare-task-rows').innerHTML.includes('任务'));assert(x.node('#compare-page').textContent.includes('当前清单 0 项'));x.node('#compare-changed').checked=false;x.fire('#compare-changed','change');assert(x.node('#compare-page').textContent.includes('198 项'));x.fire('#compare-next');assert(x.node('#compare-page').textContent.startsWith('2 /'));x.fire('#compare-material-tab');x.node('#compare-allocation-changed').checked=false;x.fire('#compare-allocation-changed','change');assert(x.node('#compare-allocation-rows').innerHTML.includes('供给'))});
await check(async()=>{const first=pending(),x=harness(path=>path==='joint-schedule'?Promise.resolve(list):first.promise),w=createJointComparison(x.h),run=w.render(new URLSearchParams(),1);await tick();x.leave();first.resolve(d);await run;assert.equal(x.node('#main').innerHTML,'')});
await check(async()=>{const old=pending();let reads=0;const x=harness(path=>path==='joint-schedule'?Promise.resolve(list):++reads===1?old.promise:Promise.resolve({...d,study:{...d.study,name:'CURRENT',scope:'LATEST'}})),w=createJointComparison(x.h),first=w.render(new URLSearchParams(),1);await tick();await w.render(new URLSearchParams(),1);old.resolve({...d,study:{...d.study,scope:'STALE'}});await first;assert(x.node('#main').innerHTML.includes('LATEST'));assert(!x.node('#main').innerHTML.includes('STALE'))});
await check(async()=>{const x=harness(normal);x.groups.set('[data-compare-policy]',[{dataset:{comparePolicy:'priority'},addEventListener:(e,f)=>x.events.set('policy',f)}]);await createJointComparison(x.h).render(new URLSearchParams(),1);x.events.get('policy')();assert.deepEqual(x.moves,[['joint-schedule',{study:d.study.id,policy:'priority',receipt:'RIGHT'}]])});
await check(async()=>{const source=pending(),x=harness(path=>path.endsWith('/sources')?source.promise:normal(path));await createJointComparison(x.h).render(new URLSearchParams(),1);const open=x.fire('#compare-sources');x.replaceModal();source.resolve({rows:[],total:0});await open;assert.deepEqual(x.modals,[])});
console.log(JSON.stringify({success:true,checks,browser_acceptance:false}));
