import assert from 'node:assert/strict';
import fs from 'node:fs';
import {taskRows,selectTasks,remainderGantt,materialsMarkup,remainderDetail,exportPath,createWipTrial} from '../static/wip_trial.js';
const d=JSON.parse(fs.readFileSync(new URL('./fixtures/wip_trial_001.json',import.meta.url),'utf8')),paused=JSON.parse(fs.readFileSync(new URL('./fixtures/wip_trial_004.json',import.meta.url),'utf8'));
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const h={esc,table:(heads,rows)=>heads.join('|')+'\n'+rows.map(r=>r.join('|')).join('\n'),panel:(a,b,c)=>a+b+c};let groups=0;
const check=async(name,f)=>{await f();groups++;console.log('PASS '+name)};
await check('four states partition 52 tasks without cross-process volume sums',()=>{assert.equal(d.tasks.length,52);assert.equal(selectTasks(d,{state:'completed'}).length,2);assert.equal(selectTasks(d,{state:'carried'}).length,1);assert.equal(selectTasks(d,{state:'scheduled'}).length,49);assert.equal(selectTasks(d,{job:d.jobs[1].id}).length,26);assert.equal(selectTasks(d,{job:d.jobs[1].id,state:'carried'}).length,0);});
await check('historical completion excluded from both future axes',()=>{for(const mode of ['resource','worker']){const html=remainderGantt(d,mode,h);assert.equal((html.match(/data-wt-task=/g)||[]).length,50);for(const t of selectTasks(d,{state:'completed'}))assert.ok(!html.includes(t.id));assert.ok(html.includes('#336bad'));assert.ok(html.includes('tabindex="0"'));assert.ok(!html.includes('NaN'));}assert.throws(()=>remainderGantt(d,'bad',h));});
await check('paused does not render zero load or false schedule',()=>{const html=remainderGantt(paused,'resource',h);assert.ok(html.includes('未生成'));assert.ok(!html.includes('<svg'));assert.equal(paused.summary,null);});
await check('quantity, exact units, zero need, embedded material and independent pools',()=>{const html=materialsMarkup(d,h);for(const text of ['已投入在制品','尚需投入','逐任务','kg','件','无需新增投入','可用量 = 已预留 + 未预留','不能据总量判断齐套'])assert.ok(html.includes(text));assert.equal(d.balances.length,8);assert.ok(taskRows(d.tasks,h).includes('实际完成'));assert.ok(taskRows(d.tasks,h).includes('原人机续作'));});
await check('all source text escapes in tables and gantt attributes',()=>{const x=structuredClone(d);x.tasks[2].id='<img>';x.tasks[2].resource_id='<svg>';x.lots[0].location='<script>';for(const [html,tag] of [[taskRows(x.tasks,h),'img'],[remainderGantt(x,'resource',h),'svg'],[materialsMarkup(x,h),'script']]){assert.ok(html.includes('&lt;'+tag+'&gt;'));assert.ok(!html.includes('<'+tag+'>'));}});
await check('source-bound download routes validate policy and format',()=>{assert.throws(()=>exportPath('W','due','','json'));assert.throws(()=>exportPath('W','bad','R','json'));assert.throws(()=>exportPath('W','due','R','xls'));assert.equal(exportPath('A/B','priority','R &','csv'),'/api/wip-trial/A%2FB/export?policy=priority&receipt=R+%26&format=csv');});
function fixture(board=d){
 let current=1,revision=0,html='';const elements=new Map(),handlers=new Map(),calls=[],pending=[];const get=k=>{if(!elements.has(k))elements.set(k,{innerHTML:'',value:'',open:false});return elements.get(k)};
 const list={rows:[{...board.study,is_latest:true}],policies:{due:'交期',priority:'优先级'}};
 const ctx={...h,header:()=>'',toast:e=>calls.push(['error',e]),go:(...a)=>calls.push(a),$:(k)=>get(k),$$:()=>[],on:(k,e,f)=>handlers.set(k+':'+e,f),isCurrent:t=>t===current,getModalRevision:()=>revision,modal:(a,b)=>{revision++;html=a+b},
  api:url=>{calls.push(url);return url==='wip-trial'?Promise.resolve(list):url.includes('/sources?')?new Promise((resolve,reject)=>pending.push({resolve,reject,url})):Promise.resolve(board)}};
 return {render:createWipTrial(ctx).render,get,handlers,calls,pending,html:()=>html,navigate:()=>{current++},replace:()=>{revision++;html='replacement'}};
}
await check('page selects exact version/policy and clear paused state',async()=>{const f=fixture(paused);await f.render(new URLSearchParams('study=WR-261001-004&policy=priority'),1);assert.ok(f.get('#main').innerHTML.includes('整个方案暂停'));assert.ok(!f.get('#main').innerHTML.includes('id="wt-body"'));assert.ok(f.calls.some(x=>typeof x==='string'&&x.includes('policy=priority')));f.handlers.get('#wt-policy:change')({target:{value:'due'}});assert.deepEqual(f.calls.at(-1),['wip-trial',{study:'WR-261001-004',policy:'due'}]);});
await check('task filter is detail-only and reset restores population',async()=>{const f=fixture();await f.render(new URLSearchParams(),1);const main=f.get('#main').innerHTML,chart=f.get('#wt-chart').innerHTML;f.get('#wt-state').value='carried';f.handlers.get('#wt-state:change')();assert.ok(f.get('#wt-tasks').innerHTML.includes('当前 1 / 全方案 52'));assert.equal(f.get('#main').innerHTML,main);assert.equal(f.get('#wt-chart').innerHTML,chart);f.handlers.get('#wt-reset:click')();assert.ok(f.get('#wt-tasks').innerHTML.includes('当前 52 / 全方案 52'));});
await check('source paging preserves receipt and closed navigation drops late response',async()=>{const f=fixture();await f.render(new URLSearchParams(),1);const p=f.handlers.get('#wt-sources:click')();assert.ok(f.pending[0].url.includes('receipt=test-only-placeholder'));f.pending[0].resolve({rows:[],total:81,size:40,page:1,can_download_original:false});await p;assert.ok(f.html().includes('不授予原件'));const q=f.handlers.get('#wt-next:click')();assert.ok(f.pending[1].url.includes('page=2'));f.navigate();const before=f.html();f.pending[1].resolve({rows:[],total:81,size:40,page:2});await q;assert.equal(f.html(),before);});
await check('replaced modal and old source errors cannot overwrite current display',async()=>{for(const reject of [false,true]){const f=fixture();await f.render(new URLSearchParams(),1);const p=f.handlers.get('#wt-sources:click')();f.replace();if(reject)f.pending[0].reject(Error('old'));else f.pending[0].resolve({rows:[],total:0,size:40,page:1});await p;assert.equal(f.html(),'replacement');assert.ok(!f.calls.some(x=>Array.isArray(x)&&x[0]==='error'));}});
console.log(JSON.stringify({success:true,groups,browser_acceptance:false}));
