import assert from 'node:assert/strict';
import fs from 'node:fs';
import {decisionMarkup,exportPath,createWipTrial} from '../static/wip_trial.js';
const fixtures=JSON.parse(fs.readFileSync(new URL('./fixtures/wip_decision.json',import.meta.url),'utf8'));
const board={...JSON.parse(fs.readFileSync(new URL('./fixtures/wip_trial_001.json',import.meta.url),'utf8')),capabilities:{task_decision:'WIP_DISPATCH_EVIDENCE_1',task_selection:'WIP_TASK_SELECTION_1'}};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const h={esc,table:(heads,rows)=>heads.join('|')+'\n'+rows.map(r=>r.join('|')).join('\n'),panel:(a,b,c)=>a+b+c};
let groups=0;const check=async(name,f)=>{await f();groups++;console.log('PASS '+name)};
await check('complete candidate matrix separates selected and feasible alternatives',()=>{const d=fixtures.scheduled,s=decisionMarkup(d,h);assert.equal((s.match(/窗口、不可用时段和资格/g)||[]).length,d.pair_count);assert.ok(s.includes('本次选中'));assert.ok(s.includes('可行，排序未选中'));assert.ok(s.includes('不表示全局最优'));assert.ok(s.includes(d.pairs[0].option_id));});
await check('carry-in shows original capacity basis and lock exclusions',()=>{const s=decisionMarkup(fixtures.carried,h);assert.ok(s.includes('原处理批量'));assert.ok(s.includes('加工中仅允许原锁定人机'));assert.ok(s.includes('完整排序值'));});
await check('historical and unavailable evidence never display fabricated pair rows',()=>{for(const d of [fixtures.completed,{...fixtures.scheduled,state:'unavailable',pairs:[],issues:['超过受控规模，未截断']}]){const s=decisionMarkup(d,h);assert.ok(!s.includes('窗口、不可用时段和资格'));}assert.ok(decisionMarkup(null,h).includes('未取得'));});
await check('blocked material does not claim all pairs lack capacity',()=>{const s=decisionMarkup(fixtures.blocked,h);assert.ok(s.includes('剩余物料不足，未计算连续窗口'));assert.ok(!s.includes('本次选中'));});
await check('preallocation balance and future supply labels remain distinct',()=>{const s=decisionMarkup(fixtures.tail,h);for(const label of ['原可用 / 此任务前余量','全方案最终余量见下方','不等于截止时已在库','尾部占用'])assert.ok(s.includes(label),label);});
await check('every tail/predecessor/root link belongs to the same task evidence',()=>{const d=fixtures.scheduled,s=decisionMarkup(d,h);for(const t of d.related_tasks)assert.ok(s.includes('data-wt-task="'+esc(t.id)+'"'));assert.ok(s.includes('直接前序'));});
await check('all candidate and source strings escape HTML',()=>{const d=structuredClone(fixtures.scheduled);d.pairs[0].resource_id='<script>';d.pairs[0].reasons=['<img>'];d.pairs[0].windows[0].resource_window_id='<svg>';d.related_tasks[0].id='" onclick="bad';const s=decisionMarkup(d,h);for(const x of ['script','img','svg']){assert.ok(s.includes('&lt;'+x+'&gt;'));assert.ok(!s.includes('<'+x+'>'));}assert.ok(s.includes('&quot; onclick=&quot;bad'));});
await check('task exports preserve exact scope with encoded IDs',()=>{assert.equal(exportPath('W/A','due','R &','json','T/B'),'/api/wip-trial/W%2FA/tasks/T%2FB/export?policy=due&receipt=R+%26&format=json');assert.throws(()=>exportPath('W','due','R','csv',''));assert.throws(()=>exportPath('W','due','R','csv',12));});
function harness(){
 let current=1,revision=0,html='';const elements=new Map(),handlers=new Map(),calls=[],pending=[];
 const get=k=>{if(!elements.has(k))elements.set(k,{innerHTML:'',value:''});return elements.get(k)};
 const target={dataset:{wtTask:board.tasks[0].id},tagName:'BUTTON',handlers:{},addEventListener(k,f){this.handlers[k]=f}};
 const d={row:board.tasks[0],progress:{basis:'SIM'},operation:null,demands:[],reservations:[],lots:[],notice:'SIM',decision:fixtures.completed};
 const ctx={...h,header:()=>'',toast:e=>calls.push(['error',e]),go:()=>{},$:get,$$:selector=>selector==='[data-wt-task]'?[target]:[],on:(k,e,f)=>handlers.set(k+':'+e,f),isCurrent:t=>t===current,getModalRevision:()=>revision,modal:(a,b)=>{revision++;html=a+b},api:url=>{calls.push(url);if(url==='wip-trial')return Promise.resolve({rows:[{...board.study,is_latest:true}],policies:{due:'交期'}});if(url.includes('/tasks/'))return new Promise((resolve,reject)=>pending.push({resolve,reject,url}));return Promise.resolve(board)}};
 return {render:createWipTrial(ctx).render,handlers,calls,pending,target,detail:d,html:()=>html,replace:()=>{revision++;html='replacement'},navigate:()=>{current++}};
}
await check('same receipt detail rejects older response after a newer drill',async()=>{const f=harness();await f.render(new URLSearchParams(),1);const a=f.target.handlers.click(),b=f.target.handlers.click();assert.ok(f.pending[0].url.includes('receipt=test-only-placeholder'));f.pending[1].resolve(f.detail);await b;const html=f.html();f.pending[0].resolve({...f.detail,notice:'OLD'});await a;assert.equal(f.html(),html);assert.ok(html.includes('本任务解释与完整依据 JSON'));});
await check('closing or replacing task dialog ignores late reads and errors',async()=>{for(const action of ['close','replace','navigate'])for(const error of [false,true]){const f=harness();await f.render(new URLSearchParams(),1);const p=f.target.handlers.click();if(action==='close')f.handlers.get('#detail:close')();else f[action]();const before=f.html();if(error)f.pending[0].reject(Error('stale'));else f.pending[0].resolve(f.detail);await p;assert.equal(f.html(),before);assert.ok(!f.calls.some(x=>Array.isArray(x)&&x[0]==='error'));}});
await check('task export after close, replacement or navigation cannot download or show an error',async()=>{const original=globalThis.fetch;try{for(const action of ['close','replace','navigate'])for(const fail of [false,true]){const f=harness();await f.render(new URLSearchParams(),1);const detail=f.target.handlers.click();f.pending[0].resolve(f.detail);await detail;let resolve;globalThis.fetch=url=>{assert.ok(url.includes('/tasks/'));assert.ok(url.includes('receipt=test-only-placeholder'));return new Promise(r=>resolve=r)};const p=f.handlers.get('#wt-task-json:click')();if(action==='close')f.handlers.get('#detail:close')();else f[action]();const before=f.html();resolve({ok:!fail,json:async()=>({error:'old'}),headers:{get:()=> 'attachment;'},blob:()=>{throw Error('stale blob read')}});await p;assert.equal(f.html(),before);assert.ok(!f.calls.some(x=>Array.isArray(x)&&x[0]==='error'));}}finally{globalThis.fetch=original;}});
console.log(JSON.stringify({success:true,groups,browser_acceptance:false}));
