import assert from 'node:assert/strict';
import fs from 'node:fs';
import {selectionExportPath,selectTasks,createWipTrial,decisionMarkup} from '../static/wip_trial.js';
const load=name=>JSON.parse(fs.readFileSync(new URL('./fixtures/'+name+'.json',import.meta.url),'utf8'));
const boards=load('wip_blockers'), selections=load('wip_selection');
const board={...load('wip_trial_001'),capabilities:{task_decision:'WIP_DISPATCH_EVIDENCE_1',task_selection:'WIP_TASK_SELECTION_1'}};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const h={esc,table:(heads,rows)=>heads.join('|')+'\n'+rows.map(r=>r.join('|')).join('\n'),panel:(a,b,c)=>a+b+c};
let groups=0;const check=async(name,f)=>{await f();groups++;console.log('PASS '+name)};
await check('export URLs preserve exact encoded filter IDs and receipt',()=>{const filters={job:'J/A & 中',state:'blocked',root:'T?B'};const url=new URL(selectionExportPath('W/A','priority','R &','csv',filters),'http://example.test');assert.equal(url.pathname,'/api/wip-trial/W%2FA/selection/export');assert.deepEqual(Object.fromEntries(url.searchParams),{policy:'priority',receipt:'R &',format:'csv',...filters});});
await check('invalid filters never silently broaden export scope',()=>{for(const scope of [{job:null},{job:undefined},{root:1},{state:false},{state:'late'},{job:'a'.repeat(201)},{extra:''}])assert.throws(()=>selectionExportPath('W','due','R','csv',scope));for(const [policy,receipt,format] of [['future','R','csv'],['due','','csv'],['due','R','xlsx']])assert.throws(()=>selectionExportPath('W',policy,receipt,format,{}));});
await check('all original Excel scope intersections match the backend independent oracle',()=>{let n=0;for(const fixture of selections){const d=boards.find(x=>x.board.study.id===fixture.study&&x.board.policy===fixture.policy).board;for(const s of fixture.selections){assert.deepEqual(selectTasks(d,s.filters).map(t=>t.id),s.task_ids);n++;}}assert.ok(n>=200);});
function harness(capabilities=board.capabilities){
 let current=1,revision=0,html='';const elements=new Map(),handlers=new Map(),calls=[];
 const get=k=>{if(!elements.has(k))elements.set(k,{innerHTML:'',value:''});return elements.get(k)};
 const task={dataset:{wtTask:board.tasks[0].id},tagName:'BUTTON',handlers:{},addEventListener(k,f){this.handlers[k]=f}};
 const root={dataset:{wtRootFocus:'unused-root'},addEventListener(k,f){this[k]=f}};
 const ctx={...h,header:()=>'',toast:e=>calls.push(['error',e]),go:()=>{current++},$:get,$$:s=>s==='[data-wt-task]'?[task]:s==='[data-wt-root-focus]'?[root]:[],on:(k,e,f)=>handlers.set(k+':'+e,f),isCurrent:t=>t===current,getModalRevision:()=>revision,modal:(a,b)=>{revision++;html=a+b},api:async url=>{calls.push(url);if(url==='wip-trial')return {rows:[{...board.study,is_latest:true}],policies:{due:'交期'}};if(url.includes('/tasks/'))return {row:board.tasks[0],progress:{basis:'SIM'},operation:null,demands:[],reservations:[],lots:[],notice:'SIM'};return {...board,capabilities}}};
 return {render:createWipTrial(ctx).render,handlers,calls,get,task,root,html:()=>html,navigate:()=>{current++}};
}
const originalFetch=globalThis.fetch, originalDocument=globalThis.document,originalCreate=URL.createObjectURL,originalRevoke=URL.revokeObjectURL,originalTimeout=globalThis.setTimeout;
const pending=[],files=[];
globalThis.fetch=url=>new Promise((resolve,reject)=>pending.push({url,resolve,reject}));
URL.createObjectURL=blob=>{files.push({blob});return 'blob:unit-test'};URL.revokeObjectURL=()=>{};globalThis.setTimeout=f=>{f();return 0};
globalThis.document={body:{append(){}},createElement:()=>({click(){files.at(-1).filename=this.download},remove(){}})};
const ok=()=>({ok:true,headers:{get:()=> 'attachment; filename="synthetic.csv"'},blob:async()=>({synthetic:true})});
const click=(f,id)=>f.handlers.get('#'+id+':click')();
try{
await check('known capability renders selected and whole export purposes separately',async()=>{const f=harness();await f.render(new URLSearchParams(),1);assert.ok(f.get('#wt-body').innerHTML.includes('筛选任务 CSV'));assert.ok(f.get('#wt-body').innerHTML.includes('复算共享竞争'));assert.ok(f.get('#main').innerHTML.includes('完整输入与结果 JSON'));});
await check('older or unknown server capabilities keep original details but hide new routes',async()=>{for(const caps of [undefined,{}, {task_selection:'FUTURE',task_decision:'FUTURE'}]){const f=harness(caps===undefined?null:caps);await f.render(new URLSearchParams(),1);assert.ok(!f.handlers.has('#wt-selected-csv:click'));assert.ok(f.get('#wt-body').innerHTML.includes('当前服务未提供筛选导出'));await f.task.handlers.click();assert.ok(f.html().includes('原报工与进度声明'));assert.ok(!f.handlers.has('#wt-task-json:click'));}assert.ok(decisionMarkup({version:'FUTURE'},h).includes('尚不受支持'));});
await check('export captures all current filters and delivers the selected attachment',async()=>{const f=harness();await f.render(new URLSearchParams(),1);f.get('#wt-job').value=board.jobs[0].id;f.get('#wt-state').value='carried';await f.handlers.get('#wt-state:change')();const before=files.length,p=click(f,'wt-selected-csv'),r=pending.at(-1),q=new URL(r.url,'http://example.test').searchParams;assert.equal(q.get('job'),board.jobs[0].id);assert.equal(q.get('state'),'carried');assert.equal(q.get('receipt'),board.receipt);r.resolve(ok());await p;assert.equal(files.length,before+1);assert.ok(files.at(-1).filename.startsWith('wip-selected-'));});
await check('filter/reset/tab/refresh/navigation invalidate pending selection response',async()=>{for(const action of ['job','state','root','reset','material','schedule','refresh','navigate']){const f=harness();await f.render(new URLSearchParams(),1);const p=click(f,'wt-selected-json'),r=pending.at(-1),before=files.length;if(['job','state','root'].includes(action))await f.handlers.get('#wt-'+action+':change')();else if(action==='navigate')f.navigate();else await click(f,action==='material'?'wt-tab-material':action==='schedule'?'wt-tab-schedule':action==='refresh'?'wt-refresh':'wt-reset');r.resolve({ok:true,blob:()=>{throw Error('must not read stale attachment')}});await p;assert.equal(files.length,before);assert.ok(!f.calls.some(x=>Array.isArray(x)&&x[0]==='error'));}});
await check('scope changes during blob read also suppress old attachment',async()=>{const f=harness();await f.render(new URLSearchParams(),1);let resolveBlob,reading;const started=new Promise(r=>reading=r),p=click(f,'wt-selected-csv'),r=pending.at(-1),before=files.length;r.resolve({...ok(),blob:()=>{reading();return new Promise(resolve=>resolveBlob=resolve)}});await started;await click(f,'wt-reset');resolveBlob({synthetic:true});await p;assert.equal(files.length,before);});
await check('latest download wins without blocking another request',async()=>{const f=harness();await f.render(new URLSearchParams(),1);const before=files.length,a=click(f,'wt-selected-csv'),old=pending.at(-1),b=click(f,'wt-selected-json'),fresh=pending.at(-1);fresh.resolve(ok());await b;old.resolve(ok());await a;assert.equal(files.length,before+1);assert.ok(files.at(-1).filename.endsWith('.json'));});
await check('stale failure is silent while current server errors remain visible',async()=>{for(const stale of [true,false]){const f=harness();await f.render(new URLSearchParams(),1);const p=click(f,'wt-selected-json'),r=pending.at(-1);if(stale)await click(f,'wt-reset');r.resolve({ok:false,json:async()=>({error:'scope expired'})});await p;assert.equal(f.calls.some(x=>Array.isArray(x)&&x[0]==='error'),!stale);}});
await check('current nonattachment is rejected and does not trigger a download',async()=>{const f=harness();await f.render(new URLSearchParams(),1);const before=files.length,p=click(f,'wt-selected-csv');pending.at(-1).resolve({...ok(),headers:{get:()=>null}});await p;assert.equal(files.length,before);assert.ok(f.calls.some(x=>Array.isArray(x)&&x[0]==='error'));});
await check('whole-plan exports retain their whole scope after local task filtering',async()=>{const f=harness();await f.render(new URLSearchParams(),1);f.get('#wt-state').value='carried';await f.handlers.get('#wt-state:change')();const p=click(f,'wt-json'),r=pending.at(-1),q=new URL(r.url,'http://example.test');assert.ok(!q.pathname.includes('/selection/'));assert.equal(q.searchParams.has('state'),false);r.resolve(ok());await p;assert.ok(files.at(-1).filename.startsWith('wip-remainder-'));});
}finally{globalThis.fetch=originalFetch;globalThis.document=originalDocument;URL.createObjectURL=originalCreate;URL.revokeObjectURL=originalRevoke;globalThis.setTimeout=originalTimeout;}
console.log(JSON.stringify({success:true,groups,browser_acceptance:false,actual_download_acceptance:false}));
