// Pure projection, HTML-string and asynchronous state checks; no browser automation.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {occupancyReport,occupancyRows,occupancyTasks,occupancyChart} from '../static/joint_occupancy.js';
import {createJointComparison} from '../static/joint_compare.js';
const fixtures=JSON.parse(fs.readFileSync(new URL('fixtures/batch_material_comparisons.json',import.meta.url)));
const d={...fixtures['MP-261009-002'],receipt:'SIM',policy_receipts:{due:'D',priority:'P'},source_count:741};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const table=(heads,rows)=>{assert(rows.every(r=>r.length===heads.length));return '<table>'+rows.map(r=>r.join('|')).join('\n')+'</table>'};
const panel=(title,actions,body)=>{assert.equal(typeof body,'string');return title+actions+body};
const names=[];async function check(name,fn){await fn();names.push(name)}
function hand(){
 const t=(id,r,e,a,b,c)=>({id,job_id:id,resource_id:r,employee_id:e,state:'scheduled',started:'2026-10-09T'+a,process_started:'2026-10-09T'+b,finished:'2026-10-09T'+c,setup_minutes:(Date.parse('2026-10-09T'+b+'Z')-Date.parse('2026-10-09T'+a+'Z'))/60000,process_minutes:(Date.parse('2026-10-09T'+c+'Z')-Date.parse('2026-10-09T'+b+'Z'))/60000});
 return {state:'compared',summary:{tasks:2},jobs:[{id:'A'},{id:'B'}],resource_study:{baseline:'2026-10-09T08:00:00',horizon_end:'2026-10-09T18:00:00'},columns:Object.fromEntries(['due','priority'].map(p=>[p,{state:'trial',summary:{tasks:2,scheduled_tasks:2,blocked_tasks:0}}])),tasks:[
 {id:'A',job_id:'A',process:'冲片',left:t('A','R1','E1','08:00:00','08:10:00','08:30:00'),right:t('A','R2','E1','08:00:00','08:00:00','08:20:00')},
 {id:'B',job_id:'B',process:'冲片',left:t('B','R1','E1','08:30:00','08:30:00','09:00:00'),right:t('B','R1','E2','08:15:00','08:25:00','08:55:00')} ]};
}
await check('hand-calculated setup and process durations reconcile by exact assigned identity',()=>{const r=occupancyReport(hand());assert.equal(r.state,'ready');const a=r.axes.resource[0];assert.equal(a.left.busy_minutes,60);assert.equal(a.right.busy_minutes,40);assert.equal(a.busy_delta_minutes,-20);assert.equal(a.left.setup_minutes,10);assert.equal(r.axes.worker[0].right.busy_minutes,20)});
await check('equipment and personnel are separate views of the same time, not additive capacity',()=>{const r=occupancyReport(hand());for(const s of ['left','right'])assert.equal(r.axes.resource.reduce((n,x)=>n+x[s].busy_minutes,0),r.axes.worker.reduce((n,x)=>n+x[s].busy_minutes,0));assert.equal(r.axes.resource[1].left.tasks.length,0)});
await check('normally imported scenarios retain shared batch recipient swaps',()=>{for(const x of Object.values(fixtures)){const r=occupancyReport(x);assert.equal(r.state,'ready');for(const s of ['left','right'])assert.equal(r.axes.resource.flatMap(x=>x[s].tasks).length,x.columns[s==='left'?'due':'priority'].summary.scheduled_tasks)}assert.equal(occupancyReport(fixtures['MP-261009-001']).summary.left_blocked,26)});
await check('equal occupied minutes can still contain different assigned tasks',()=>{const x=hand();x.tasks[0].right=structuredClone(x.tasks[0].left);x.tasks[1].right=structuredClone(x.tasks[1].left);[x.tasks[0].right.started,x.tasks[1].right.started]=[x.tasks[1].right.started,x.tasks[0].right.started];[x.tasks[0].right.process_started,x.tasks[1].right.process_started]=[x.tasks[1].right.process_started,x.tasks[0].right.process_started];[x.tasks[0].right.finished,x.tasks[1].right.finished]=[x.tasks[1].right.finished,x.tasks[0].right.finished];[x.tasks[0].right.setup_minutes,x.tasks[1].right.setup_minutes]=[x.tasks[1].right.setup_minutes,x.tasks[0].right.setup_minutes];[x.tasks[0].right.process_minutes,x.tasks[1].right.process_minutes]=[x.tasks[1].right.process_minutes,x.tasks[0].right.process_minutes];const r=occupancyReport(x);assert.equal(r.axes.resource[0].busy_delta_minutes,0);assert(r.axes.resource[0].changed)});
await check('paused input does not become zero occupancy',()=>{const r=occupancyReport({state:'paused',summary:null});assert.equal(r.state,'paused');assert.equal(r.summary,null);assert(occupancyChart(r,[],{esc}).includes('未计算'))});
await check('empty valid schedule has no invented resources or healthy allocation',()=>{const x=hand();for(const row of x.tasks)for(const s of ['left','right'])Object.assign(row[s],{state:'blocked',started:null,process_started:null,finished:null});for(const c of Object.values(x.columns))Object.assign(c.summary,{scheduled_tasks:0,blocked_tasks:2});const r=occupancyReport(x);assert.equal(r.state,'ready');assert.equal(r.axes.resource.length,0);assert.equal(r.summary.left_blocked,2);assert(occupancyChart(r,[],{esc}).includes('未排任务'))});
await check('missing, duplicate and inconsistent scope is unavailable',()=>{for(const mutate of [x=>x.tasks.pop(),x=>x.tasks[1].id=x.tasks[0].id,x=>x.tasks[0].left.id='X',x=>x.tasks[0].left.resource_id='',x=>x.tasks[0].job_id='UNKNOWN',x=>x.columns.due.summary.scheduled_tasks=0]){const x=hand();mutate(x);assert.equal(occupancyReport(x).state,'unavailable')}});
await check('invalid dates, wrong durations and out-of-range tasks stop projection',()=>{for(const mutate of [x=>x.tasks[0].left.started='2026-02-30T08:00:00',x=>x.tasks[0].left.finished=null,x=>x.tasks[0].left.setup_minutes=11,x=>x.resource_study.baseline='2026-10-09T08:05:00',x=>x.tasks[0].left.state='blocked']){const x=hand();mutate(x);assert.equal(occupancyReport(x).state,'unavailable')}});
await check('overlapping worker or resource intervals are rejected while adjacent tasks remain valid',()=>{const x=hand();x.tasks[1].right.employee_id='E1';assert.equal(occupancyReport(x).state,'unavailable');assert.equal(occupancyReport(hand()).state,'ready')});
await check('filters and pagination preserve common time range and complete report',()=>{const r=occupancyReport(d),before=structuredClone(r);assert.equal(occupancyRows(r).rows.length,8);assert.equal(occupancyRows(r,{page:3}).rows.length,1);const id=r.axes.resource[0].id;assert.equal(occupancyRows(r,{entity:id}).total,1);assert(occupancyRows(r,{changed:true}).rows.every(x=>x.changed));assert.deepEqual(r,before)});
await check('same common extent appears for both axes, pages and selected entities',()=>{const r=occupancyReport(d),axis=html=>html.match(/<div class="occupancy-axis">[\s\S]*?<\/div><\/div>/)[0].replace(/<b>.*?<\/b>/,'');assert.equal(axis(occupancyChart(r,r.axes.resource.slice(0,8),{esc})),axis(occupancyChart(r,r.axes.worker.slice(8,16),{esc,axis:'worker'})));assert.notEqual(axis(occupancyChart(r,r.axes.resource,{esc})),axis(occupancyChart(r,r.axes.resource,{esc,range:'full'})))});
await check('time coordinates are timezone independent and chart includes exact task labels',()=>{const r=occupancyReport(hand()),html=occupancyChart(r,r.axes.resource,{esc,range:'full'});assert(html.includes('width:5%'));assert(html.includes('width:33.33333333333333%'));assert(html.includes('准备 2026-10-09 08:00:00'));assert(html.includes('aria-label='));assert(html.includes('该策略未分配任务'))});
await check('object drill includes assignments on either side without duplicates',()=>{const x=hand();assert.deepEqual(occupancyTasks(x.tasks,{axis:'resource',id:'R1'}).map(r=>r.id),['A','B']);assert.deepEqual(occupancyTasks(x.tasks,{axis:'worker',id:'E2'}).map(r=>r.id),['B']);assert.equal(occupancyTasks(x.tasks,{axis:'bad',id:'E2'}).length,0)});
await check('HTML labels and identities are escaped; input objects are not mutated',()=>{const x=hand(),before=structuredClone(x);occupancyReport(x);assert.deepEqual(x,before);const r=occupancyReport(x);r.axes.resource[0].id='<img src=x>';r.axes.resource[0].left.tasks[0].id='" onfocus="x';const html=occupancyChart(r,r.axes.resource,{esc});assert(!html.includes('<img'));assert(!html.includes('data-occupancy-task="" onfocus='))});
const pending=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve}};
function setup(intercept){
 const nodes=new Map(),events=new Map(),requests=[],modals=[];let active=true,revision=0;
 const node=id=>{if(!nodes.has(id))nodes.set(id,{innerHTML:'',value:'',checked:true,textContent:'',disabled:false});return nodes.get(id)};
 const report=occupancyReport(d),id=report.axes.resource[0].id,task=report.axes.resource[0].left.tasks[0].id;
 const object={dataset:{occupancyEntity:id,occupancyAxis:'resource'},addEventListener:(name,fn)=>events.set('object:'+name,fn)};
 const mark={dataset:{occupancyTask:task},addEventListener:(name,fn)=>events.set('mark:'+name,fn)};
 const api=(path,options)=>{requests.push({path,options});const value=intercept?.(path,options);if(value!==undefined)return Promise.resolve(value);if(path==='joint-schedule')return Promise.resolve({rows:[d.study]});if(path.endsWith('/sources'))return Promise.resolve({rows:[],page:1,total:741,size:40});if(path.includes('/tasks/'))return Promise.resolve({task:d.tasks.find(t=>t.id===task),left:{demands:[],reservations:[]},right:{demands:[],reservations:[]},notice:'SIM'});return Promise.resolve(structuredClone(d))};
 return {node,events,requests,modals,object,mark,leave:()=>active=false,fire:(id,event='click')=>events.get(id+':'+event)({}),h:{esc,table,panel,api,$:node,$$:s=>s==='[data-occupancy-entity]'?[object]:s==='[data-occupancy-task]'?[mark]:[],on:(id,event,fn)=>events.set(id+':'+event,fn),header:(...v)=>v.join(''),modal:(...v)=>{revision++;modals.push(v)},toast:()=>{},go:()=>{},isCurrent:()=>active,getModalRevision:()=>revision}};
}
async function open(x){await createJointComparison(x.h).render(new URLSearchParams({study:d.study.id}),1);x.fire('#compare-occupancy-tab')}
await check('occupancy tab renders common-axis chart and full-scope quantities',async()=>{const x=setup();await open(x);assert(x.node('#occupancy-chart').innerHTML.includes('occupancy-plot'));assert(x.node('#occupancy-summary').textContent.includes('52 项'));assert(x.node('#compare-body').innerHTML.includes('不作利用率'))});
await check('axis switch clears old identity, paging and entity filter retain scope',async()=>{const x=setup();await open(x);x.fire('#occupancy-next');assert(x.node('#occupancy-page').textContent.startsWith('2 /'));x.node('#occupancy-axis').value='worker';x.fire('#occupancy-axis','change');assert.equal(x.node('#occupancy-entity').value,'');assert(x.node('#occupancy-page').textContent.startsWith('1 /'));assert(x.node('#occupancy-chart').innerHTML.includes('原操作工号'))});
await check('object drill resets unrelated restrictions and manual job selection intersects',async()=>{const x=setup();await open(x);x.fire('object');const related=occupancyTasks(d.tasks,{axis:'resource',id:x.object.dataset.occupancyEntity});assert.equal(x.node('#compare-changed').checked,false);assert(x.node('#compare-page').textContent.includes(`当前清单 ${related.length} 项`));x.node('#compare-job').value=d.jobs[0].id;x.fire('#compare-job','change');assert(x.node('#compare-page').textContent.includes(`当前清单 ${related.filter(t=>t.job_id===d.jobs[0].id).length} 项`));x.fire('#compare-task-reset');assert(x.node('#compare-page').textContent.includes('当前清单 52 项'))});
await check('time extent and axis persist across tabs but reread resets them',async()=>{const x=setup();await open(x);x.node('#occupancy-range').value='full';x.fire('#occupancy-range','change');x.node('#occupancy-axis').value='worker';x.fire('#occupancy-axis','change');x.fire('#compare-material-tab');x.fire('#compare-occupancy-tab');assert.equal(x.node('#occupancy-range').value,'full');assert.equal(x.node('#occupancy-axis').value,'worker');await x.fire('#compare-refresh');x.fire('#compare-occupancy-tab');assert.equal(x.node('#occupancy-axis').value,'resource');assert.equal(x.node('#occupancy-range').value,'occupied')});
await check('task click reads original two-column evidence under current receipt',async()=>{const x=setup();await open(x);await x.fire('mark');assert(x.requests.at(-1).path.endsWith('/tasks/'+x.mark.dataset.occupancyTask));assert.deepEqual(x.requests.at(-1).options.body,{receipt:'SIM'});assert.equal(x.modals.length,1)});
await check('scope change cancels pending modal response',async()=>{const p=pending(),x=setup(path=>path.includes('/tasks/')?p.promise:undefined);await open(x);const request=x.fire('mark');x.node('#occupancy-range').value='full';x.fire('#occupancy-range','change');p.resolve({});await request;assert.equal(x.modals.length,0)});
await check('forged task or entity identity cannot open unrelated evidence',async()=>{const x=setup();await open(x);x.object.dataset.occupancyEntity='INVALID';x.fire('object');x.mark.dataset.occupancyTask='INVALID';await x.fire('mark');assert.equal(x.modals.length,0);assert(!x.requests.some(r=>r.path.includes('/tasks/')))});
await check('local occupancy selection does not narrow sources or full export',async()=>{const p=pending(),x=setup(path=>path.endsWith('/export')?p.promise:undefined);await open(x);x.fire('object');await x.fire('#compare-sources');assert.deepEqual(x.requests.at(-1).options.body,{receipt:'SIM',page:1});const request=x.fire('#compare-json');assert.deepEqual(x.requests.at(-1).options.body,{receipt:'SIM',format:'json'});x.leave();p.resolve({});await request});
console.log(JSON.stringify({success:true,checks:names.length,names,browser_acceptance:false}));
