// Pure result/HTML/state tests only. No browser, DOM or automation acceptance.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {WIP_BLOCKER_VERSION,wipBlockerReport,wipTaskSelection,wipBlockerQueue} from '../static/wip_blockers.js';
import {createWipTrial} from '../static/wip_trial.js';
const cases=JSON.parse(fs.readFileSync(new URL('./fixtures/wip_blockers.json',import.meta.url),'utf8'));
const clear=JSON.parse(fs.readFileSync(new URL('./fixtures/wip_trial_001.json',import.meta.url),'utf8'));
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const h={esc,table:(headers,rows)=>headers.join('|')+'\n'+rows.map(r=>r.join('|')).join('\n'),panel:(a,b,c)=>a+b+c};let groups=0;
const check=async(name,f)=>{await f();groups++;console.log('PASS '+name)};
const task=(id,job_id,state,predecessors,root_tasks,finished=null)=>({id,job_id,state,predecessors,root_tasks,finished,process:'模拟工序',branch:'定子',reason:state==='blocked'?'模拟阻断':''});
const manual={state:'trial',study:{id:'MANUAL',version:1},policy:'due',rule_version:'WIP_REMAINDER_SHARED_POOLS_1',
 work_orders:[{job_id:'J1',work_order_id:'WO-1'},{job_id:'J2',work_order_id:'WO-2'}],
 tasks:[task('D','J1','completed',[],[],'2026-10-01T07:50:00'),task('R','J1','carried',['D'],[],'2026-10-01T08:30:00'),task('A','J1','blocked',[],['A']),task('B','J1','blocked',[],['B']),task('C','J1','blocked',['A','B'],['A','B']),task('E','J1','blocked',['C','R'],['A','B']),task('F','J2','blocked',[],['F']),task('G','J2','blocked',['F'],['F']),task('H','J2','scheduled',[],[],'2026-10-01T09:00:00')],
 jobs:[{id:'J1',qty:8,due:'2026-10-03T12:00:00',state:'blocked',finished:null,actual_completed_tasks:1,remaining_tasks:5},{id:'J2',qty:12,due:'2026-10-02T12:00:00',state:'blocked',finished:null,actual_completed_tasks:0,remaining_tasks:3}],
 summary:{tasks:9,jobs:2,qty:20,historical_completed_tasks:1,carried_tasks:1,scheduled_tasks:1,blocked_tasks:6,covered_jobs:0,late_jobs:0,blocked_jobs:2}};
await check('hand oracle preserves four states and nonadditive root memberships',()=>{const r=wipBlockerReport(manual);assert.equal(r.state,'blocked',r.issues);assert.equal(r.version,WIP_BLOCKER_VERSION);assert.deepEqual(r.summary,{roots:3,tasks:6,jobs:2,whole_job_qty:20,overlapping_tasks:2});assert.deepEqual(r.rows.map(r=>r.id),['F','A','B']);assert.equal(r.rows.reduce((n,r)=>n+r.tasks,0),8);assert.equal(r.rows.reduce((n,r)=>n+r.whole_job_qty,0),28);assert.deepEqual(r.rows.find(r=>r.id==='A').task_ids,['A','C','E']);});
await check('all 16 imported cases match independent downstream graph oracle',()=>{for(const {board,expected} of cases){const r=wipBlockerReport(board);assert.equal(r.state,expected.state,board.study.id+': '+r.issues);assert.deepEqual(r.summary,expected.summary);assert.deepEqual(r.rows,expected.rows);}});
await check('reordering source arrays cannot change queue or stable identity',()=>{const d=structuredClone(manual);d.tasks.reverse();d.jobs.reverse();d.work_orders.reverse();d.tasks.find(t=>t.id==='C').predecessors.reverse();d.tasks.find(t=>t.id==='C').root_tasks.reverse();assert.deepEqual(wipBlockerReport(d),wipBlockerReport(manual));});
await check('clear keeps due/approval caveats and paused never becomes zero',()=>{const r=wipBlockerReport(clear);assert.equal(r.state,'clear');assert.ok(wipBlockerQueue(r,h).includes('仍须分别核对'));const p=wipBlockerReport({state:'paused'});assert.equal(p.summary,null);assert.deepEqual(p.rows,[]);assert.ok(wipBlockerQueue(p,h).includes('未计算'));});
await check('unknown duplicate or nonancestor roots stop grouping',()=>{for(const mutate of [d=>d.tasks[4].root_tasks=['X'],d=>d.tasks[4].root_tasks=['A','A'],d=>d.tasks[4].root_tasks=['F'],d=>d.tasks[4].root_tasks=['C'],d=>d.tasks[4].root_tasks=['A']]){const d=structuredClone(manual);mutate(d);const r=wipBlockerReport(d);assert.equal(r.state,'paused');assert.equal(r.summary,null);assert.deepEqual(r.rows,[]);}});
await check('predecessor truncation cycles duplicate edges and cross-job links rejected',()=>{for(const mutate of [d=>d.tasks[4].predecessors=['A'],d=>d.tasks[2].predecessors=['E'],d=>d.tasks[4].predecessors=['A','A','B'],d=>d.tasks[4].predecessors=['F'],d=>d.tasks[4].predecessors=['MISSING']]){const d=structuredClone(manual);mutate(d);assert.equal(wipBlockerReport(d).state,'paused');}});
await check('successful task cannot retain blocked predecessor or root',()=>{for(const mutate of [d=>Object.assign(d.tasks[4],{state:'scheduled',root_tasks:[],finished:'2026-10-01T10:00:00'}),d=>d.tasks[0].root_tasks=['A'],d=>d.tasks[2].finished='2026-10-01T10:00:00']){const d=structuredClone(manual);mutate(d);assert.equal(wipBlockerReport(d).state,'paused');}});
await check('original work orders must map one-to-one with every job',()=>{for(const mutate of [d=>d.work_orders.pop(),d=>d.work_orders[0].work_order_id=d.work_orders[1].work_order_id,d=>d.work_orders[0].job_id='UNKNOWN',d=>d.work_orders.push(d.work_orders[0])]){const d=structuredClone(manual);mutate(d);assert.equal(wipBlockerReport(d).state,'paused');}});
await check('each state count job total and result finish reconcile',()=>{for(const mutate of [d=>d.summary.carried_tasks++,d=>d.summary.scheduled_tasks++,d=>d.summary.historical_completed_tasks++,d=>d.summary.covered_jobs++,d=>d.jobs[0].remaining_tasks--,d=>d.jobs[0].actual_completed_tasks++,d=>d.jobs[0].state='covered',d=>d.jobs[0].finished='2026-10-02T08:00:00',d=>d.tasks.pop(),d=>d.tasks.push(d.tasks[0])]){const d=structuredClone(manual);mutate(d);assert.equal(wipBlockerReport(d).state,'paused');}});
await check('unknown unsafe quantities and impossible dates are not zero or valid',()=>{for(const value of [undefined,null,0,-1,1.5,'8',Number.MAX_SAFE_INTEGER+1]){const d=structuredClone(manual);d.jobs[0].qty=value;assert.equal(wipBlockerReport(d).state,'paused');}for(const value of ['',null,'2026-02-30T12:00:00','2026-10-01','2026-10-01T12:00:00Z']){const d=structuredClone(manual);d.jobs[0].due=value;assert.equal(wipBlockerReport(d).state,'paused');}const d=structuredClone(manual);d.jobs[0].qty=Number.MAX_SAFE_INTEGER;assert.equal(wipBlockerReport(d).state,'paused');});
await check('three dimensions intersect without changing original rows',()=>{const r=wipBlockerReport(manual),before=structuredClone(manual);assert.deepEqual(wipTaskSelection(manual,r,{root:'A'}).map(t=>t.id),['A','C','E']);assert.deepEqual(wipTaskSelection(manual,r,{root:'A',job:'J2'}),[]);assert.deepEqual(wipTaskSelection(manual,r,{root:'A',state:'carried'}),[]);assert.deepEqual(wipTaskSelection(manual,r,{job:'J1',state:'completed'}).map(t=>t.id),['D']);assert.deepEqual(wipTaskSelection(manual,r,{}),manual.tasks);assert.deepEqual(manual,before);for(const scope of [{root:'a'},{job:'J'},{state:'late'}])assert.throws(()=>wipTaskSelection(manual,r,scope));});
await check('old reports cannot filter another policy version source or task graph',()=>{const r=wipBlockerReport(manual);for(const mutate of [d=>d.policy='priority',d=>d.study.version++,d=>d.study.id='DIFFERENT',d=>d.source_hash='changed',d=>d.tasks[4].root_tasks=['A'],d=>d.receipt='changed']){const d=structuredClone(manual);mutate(d);assert.throws(()=>wipTaskSelection(d,r,{root:'A'}));}});
await check('whole job quantities carry the explicit nonadditive scope',()=>{const s=wipBlockerQueue(wipBlockerReport(manual),h);for(const text of ['6 项未排任务','2 张工单 / 整单 20 台','不能跨行相加','不是剩余产量、损失产量或真实延期量','不是现场根因诊断或派工优先级','完整导出范围不变','不能把关联任务数当作可恢复产量','WO-1','最早假设交期'])assert.ok(s.includes(text),text);assert.ok(!s.includes('undefined'));});
await check('queue pagination is complete without hiding global totals',()=>{const r=wipBlockerReport(manual);r.rows=Array.from({length:49},(_,i)=>({...r.rows[0],id:'R'+i}));r.summary.roots=49;const seen=[];for(let page=1;page<=3;page++){const s=wipBlockerQueue(r,h,{page});seen.push(...[...s.matchAll(/data-wt-root-focus="([^"]+)"/g)].map(x=>x[1]));assert.ok(s.includes('49 个首阻断'));}assert.deepEqual(seen,r.rows.map(r=>r.id));assert.throws(()=>wipBlockerQueue(r,h,{page:4}));assert.throws(()=>wipBlockerQueue(r,h,{size:0}));assert.throws(()=>wipBlockerQueue(r,h,{page:0}));});
await check('source text and identity attributes are escaped',()=>{const r=wipBlockerReport(manual);Object.assign(r.rows[0],{id:'" onclick="bad',reason:'<script>',process:'<img>',work_order_id:'<svg>',work_order_ids:['<svg>']});const s=wipBlockerQueue(r,h);for(const tag of ['script','img','svg']){assert.ok(s.includes('&lt;'+tag+'&gt;'));assert.ok(!s.includes('<'+tag+'>'));}assert.ok(s.includes('&quot; onclick=&quot;bad'));});
await check('covered-but-late jobs have no invented blocker or on-time claim',()=>{const d=structuredClone(clear);for(const job of d.jobs){job.due='2026-10-01T18:00:00';job.state='late';}d.summary.late_jobs=d.jobs.length;const r=wipBlockerReport(d);assert.equal(r.state,'clear',r.issues);assert.equal(r.summary.tasks,0);assert.ok(wipBlockerQueue(r,h).includes('假设交期'));});
await check('oversized task lists or root memberships explicitly stop without truncation',()=>{const d=structuredClone(manual);d.tasks=Array.from({length:5001},(_,i)=>task('R'+i,'J1','blocked',[],['R'+i]));let r=wipBlockerReport(d);assert.equal(r.state,'paused');assert.ok(r.issues[0].includes('超过5000'));const ids=Array.from({length:500},(_,i)=>'R'+i);d.tasks=ids.map(id=>task(id,'J1','blocked',[],[id]));for(let i=0;i<400;i++)d.tasks.push(task('JOIN'+i,'J1','blocked',ids,ids));r=wipBlockerReport(d);assert.equal(r.state,'paused');assert.ok(r.issues[0].includes('超过200000'));assert.equal(r.summary,null);assert.deepEqual(r.rows,[]);d.tasks=ids.map(id=>task(id,'J1','completed',[],[],'2026-10-01T07:50:00'));for(let i=0;i<401;i++)d.tasks.push(task('JOIN'+i,'J1','completed',ids,[],'2026-10-01T07:50:00'));r=wipBlockerReport(d);assert.equal(r.state,'paused');assert.ok(r.issues[0].includes('前序关联超过200000'));});
await check('unsupported rule versions and missing explanation fields cannot appear verified',()=>{for(const mutate of [d=>d.rule_version='FUTURE_RULE',d=>d.policy='unknown',d=>d.study.version=0,d=>d.study.id='',d=>delete d.tasks[2].reason,d=>d.tasks[2].reason='',d=>delete d.tasks[2].process]){const d=structuredClone(manual);mutate(d);const r=wipBlockerReport(d);assert.equal(r.state,'paused');assert.equal(r.summary,null);assert.deepEqual(r.rows,[]);}});
function harness(){
 const b={...clear,...cases.find(c=>c.board.study.id==='WR-261001-002'&&c.board.policy==='due').board},r=wipBlockerReport(b);
 let current=1,revision=0,html='',focus=[];const nodes=new Map(),handlers=new Map(),pending=[],calls=[],taskLinks=[];
 const get=k=>{if(!nodes.has(k))nodes.set(k,{innerHTML:'',value:''});return nodes.get(k)};
 const element=(dataset)=>({dataset,tagName:'BUTTON',actions:{},addEventListener(e,f){this.actions[e]=f}});
 const ctx={...h,header:()=>'',toast:m=>calls.push(['error',m]),go:()=>{},$:get,$$:selector=>{if(selector==='[data-wt-root-focus]'){focus=r.rows.map(x=>element({wtRootFocus:x.id}));return focus;}if(selector==='[data-wt-task]'){if(!taskLinks.length)taskLinks.push(...r.rows.map(x=>element({wtTask:x.id})));return taskLinks;}return [];},on:(k,e,f)=>handlers.set(k+':'+e,f),isCurrent:t=>t===current,getModalRevision:()=>revision,modal:(a,b)=>{revision++;html=a+b},api:url=>{calls.push(url);if(url==='wip-trial')return Promise.resolve({rows:[{...b.study,is_latest:true}],policies:{due:'交期'}});if(url.includes('/tasks/'))return new Promise((resolve,reject)=>pending.push({resolve,reject,url}));return Promise.resolve(b)}};
 return {render:createWipTrial(ctx).render,b,r,get,handlers,calls,pending,html:()=>html,focus:()=>focus,taskLinks,replace:()=>{revision++;html='replacement'},navigate:()=>{current++}};
}
await check('root focus resets conflicting job and state then intersects all filters',async()=>{const f=harness();await f.render(new URLSearchParams(),1);const before=f.get('#main').innerHTML,chart=f.get('#wt-chart').innerHTML;f.get('#wt-job').value=f.b.jobs[1].id;f.get('#wt-state').value='completed';const root=f.r.rows[0];await f.focus()[0].actions.click();assert.equal(f.get('#wt-job').value,'');assert.equal(f.get('#wt-state').value,'blocked');assert.equal(f.get('#wt-root').value,root.id);assert.ok(f.get('#wt-tasks').innerHTML.includes('当前 '+root.tasks+' /'));assert.equal(f.get('#main').innerHTML,before);assert.equal(f.get('#wt-chart').innerHTML,chart);f.get('#wt-state').value='carried';await f.handlers.get('#wt-state:change')();assert.ok(f.get('#wt-tasks').innerHTML.includes('此明细交集没有任务'));await f.handlers.get('#wt-reset:click')();for(const field of ['job','state','root'])assert.equal(f.get('#wt-'+field).value,'');assert.ok(f.get('#wt-tasks').innerHTML.includes('当前 52 /'));});
await check('root detail uses the same receipt and later filter change cancels response',async()=>{const f=harness();await f.render(new URLSearchParams(),1);const p=f.taskLinks[0].actions.click();assert.ok(f.pending[0].url.includes('/tasks/'+f.r.rows[0].id+'?'));assert.ok(f.pending[0].url.includes('receipt=test-only-placeholder'));f.get('#wt-state').value='completed';await f.handlers.get('#wt-state:change')();f.pending[0].resolve({invalid:'must not be read'});await p;assert.equal(f.html(),'');assert.ok(!f.calls.some(c=>Array.isArray(c)&&c[0]==='error'));});
console.log(JSON.stringify({success:true,groups,imported_cases:cases.length,browser_acceptance:false}));
