# Generated by Django 5.2.17 on 2026-10-02 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('dataset', models.CharField(max_length=64)),
                ('definition', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.CharField(default='system', max_length=150)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('actor', models.CharField(default='local_demo', max_length=150)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=255)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=40)),
                ('date_format', models.CharField(default='%Y%m%d', max_length=20)),
                ('width', models.PositiveSmallIntegerField(default=5)),
                ('separator', models.CharField(default='-', max_length=4)),
                ('reset_period', models.CharField(default='day', max_length=10)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_path', models.TextField()),
                ('status', models.CharField(default='staging', max_length=24)),
                ('mapping', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('committed_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueDisposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='待处理', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=list)),
                ('filters', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('owner', models.CharField(default='system', max_length=150)),
                ('is_public', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CodeAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('rule_version', models.PositiveIntegerField()),
                ('allocated_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.codingrule')),
            ],
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet', models.CharField(max_length=100)),
                ('row_number', models.PositiveIntegerField()),
                ('dataset', models.CharField(db_index=True, max_length=64)),
                ('business_key', models.CharField(blank=True, max_length=255)),
                ('raw', models.JSONField(default=dict)),
                ('normalized', models.JSONField(default=dict)),
                ('record_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(db_index=True, default='valid', max_length=24)),
                ('issues', models.JSONField(default=list)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='app.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64)),
                ('business_key', models.CharField(max_length=255)),
                ('values', models.JSONField()),
                ('record_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.importrow')),
            ],
        ),
        migrations.CreateModel(
            name='CodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=30)),
                ('value', models.PositiveIntegerField(default=0)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.codingrule')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('rule', 'period'), name='coding_rule_period_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'status'], name='app_importr_batch_i_5c2f41_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['dataset', 'business_key'], name='app_record_dataset_0c5f0a_idx'),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.UniqueConstraint(fields=('dataset', 'business_key'), name='record_business_key_unique'),
        ),
    ]
