# Generated by Django 5.2.17 on 2026-10-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('keep', '保留正式记录'), ('replace', '批准替换')], max_length=16)),
                ('actor', models.CharField(max_length=150)),
                ('reason', models.TextField()),
                ('candidate_hash', models.CharField(max_length=64)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='decision', to='app.importrow')),
            ],
        ),
    ]
