# Generated by Django 5.2.17 on 2026-10-03 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_disposition_deadline_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('dataset', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetricVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('calculation_hash', models.CharField(max_length=64)),
                ('contributors', models.JSONField(default=list)),
                ('submitted_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('review_note', models.TextField(blank=True)),
                ('evidence', models.JSONField(default=dict)),
                ('published_at', models.DateTimeField(null=True)),
                ('retired_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app.governedmetric')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('metric', 'version'), name='metric_version_unique'), models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'review'])), fields=('metric',), name='metric_one_open_version')],
            },
        ),
    ]
