# Generated by Django 5.2.17 on 2026-10-03 03:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_governed_metrics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=150)),
                ('owner', models.CharField(max_length=150)),
                ('due_date', models.DateField(null=True)),
                ('status', models.CharField(default='排查中', max_length=30)),
                ('note', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
