# Generated by Django 5.2.17 on 2026-10-03 06:17

import django.db.models.deletion
from datetime import datetime
from django.db import migrations, models

def preserve_current_rules(apps,schema_editor):
    Rule=apps.get_model('app','CodingRule');Version=apps.get_model('app','CodingRuleVersion')
    Allocation=apps.get_model('app','CodeAllocation');Audit=apps.get_model('app','AuditEvent')
    fields=['name','prefix','date_format','width','separator','reset_period']
    for rule in Rule.objects.all():
        payload={k:getattr(rule,k) for k in fields}
        Version.objects.create(rule_id=rule.pk,version=rule.version,payload=payload,status='active',
            origin='legacy_snapshot',created_by='migration',reason='保留改造时当前规则快照；不补造旧版本、过去的生效日期或业务日期。')
        for event in Audit.objects.filter(action='coding.allocate',object_type='CodingRule',object_id=str(rule.pk)).order_by('id'):
            detail=event.detail
            if detail.get('version')!=rule.version:continue
            period=detail.get('period','')
            try:
                fmt={'day':'%Y%m%d','month':'%Y%m','year':'%Y'}.get(rule.reset_period)
                at=datetime.strptime(period,fmt) if fmt else None
            except (ValueError,TypeError):continue
            for a in Allocation.objects.filter(rule_id=rule.pk,rule_version=rule.version,code__in=detail.get('codes',[])):
                # Only recover evidence that the old allocation audit can prove.
                try:
                    sequence=int(a.code[-rule.width:])
                    if at is None and rule.date_format:continue
                    rendered=rule.separator.join(x for x in [rule.prefix,at.strftime(rule.date_format) if at and rule.date_format else '',str(sequence).zfill(rule.width)] if x)
                    if not 0<sequence<10**rule.width or rendered!=a.code:continue
                except (TypeError,ValueError):continue
                a.period=period;a.sequence=sequence
                a.business_date=at.date() if rule.reset_period=='day' else None
                a.definition={'version':rule.version,'payload':payload,'origin':'legacy_audit_checked','audit_event_id':event.pk}
                a.save(update_fields=['period','sequence','business_date','definition'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_trace_case_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeallocation',
            name='business_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codeallocation',
            name='definition',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='codeallocation',
            name='period',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='codeallocation',
            name='sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codingrule',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='codecounter',
            name='value',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CodeIssueRequest',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('payload_hash', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=150)),
                ('purpose', models.CharField(max_length=300)),
                ('business_date', models.DateField()),
                ('codes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.codingrule')),
            ],
        ),
        migrations.AddField(
            model_name='codeallocation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.codeissuerequest'),
        ),
        migrations.CreateModel(
            name='CodingRuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('origin', models.CharField(default='authored', max_length=30)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.CharField(blank=True, max_length=150)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app.codingrule')),
            ],
        ),
        migrations.AddField(
            model_name='codeissuerequest',
            name='rule_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.codingruleversion'),
        ),
        migrations.AddConstraint(
            model_name='codingruleversion',
            constraint=models.UniqueConstraint(fields=('rule', 'version'), name='coding_version_unique'),
        ),
        migrations.RunPython(preserve_current_rules,migrations.RunPython.noop),
    ]
