# Generated by Django 5.2.17 on 2026-10-03 08:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_costscenario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=240)),
                ('kind', models.CharField(max_length=12)),
                ('size', models.PositiveIntegerField()),
                ('file_hash', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('parsed', models.JSONField()),
                ('metadata_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFileReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('session_id', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=20)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='app.devicefile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('file', 'version'), name='device_review_version_unique')],
            },
        ),
    ]
