# Generated by Django 5.2.17 on 2026-10-03 10:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_devicefile_devicefilereview'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGrouping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'code'), name='grouping_owner_code_unique')],
            },
        ),
        migrations.CreateModel(
            name='BusinessGroupingVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grouping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app.businessgrouping')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('grouping', 'version'), name='grouping_version_unique')],
            },
        ),
    ]
