# Generated by Django 5.2.17 on 2026-10-03 12:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_businessgrouping_businessgroupingversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMonitorPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(max_length=64, unique=True)),
                ('owner', models.CharField(max_length=150)),
                ('business_clock', models.CharField(blank=True, max_length=64)),
                ('max_business_lag_days', models.FloatField(null=True)),
                ('max_import_age_hours', models.PositiveIntegerField(null=True)),
                ('note', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.CharField(max_length=150)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataQualityScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('actor', models.CharField(max_length=150)),
                ('source_revision', models.JSONField()),
                ('engine_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
