# Generated by Django 5.2.17 on 2026-10-04 05:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_account_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTaskLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dataset', models.CharField(max_length=64)),
                ('business_key', models.CharField(max_length=255)),
                ('rule', models.CharField(max_length=40)),
                ('classification', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('state', models.CharField(db_index=True, default='reported', max_length=20)),
                ('due_date', models.DateField(null=True)),
                ('source_snapshot', models.JSONField()),
                ('submission', models.JSONField(default=dict)),
                ('cycle', models.PositiveIntegerField(default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('closed_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_action_tasks', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_action_tasks', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_action_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionTaskEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=20)),
                ('request_id', models.UUIDField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('note', models.TextField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.actiontask')),
            ],
        ),
        migrations.AddConstraint(
            model_name='actiontask',
            constraint=models.UniqueConstraint(fields=('dataset', 'business_key', 'rule'), name='action_task_source_rule_unique'),
        ),
        migrations.AddConstraint(
            model_name='actiontaskevent',
            constraint=models.UniqueConstraint(fields=('task', 'sequence'), name='action_event_sequence_unique'),
        ),
        migrations.AddConstraint(
            model_name='actiontaskevent',
            constraint=models.UniqueConstraint(fields=('actor', 'request_id'), name='action_request_unique'),
        ),
    ]
