# Generated by Django 5.2.17 on 2026-10-06 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_file_read_grants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=80)),
                ('owner', models.CharField(max_length=150)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportTemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('content_hash', models.CharField(max_length=64)),
                ('state', models.CharField(default='draft', max_length=16)),
                ('reason', models.TextField()),
                ('created_by', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_by', models.CharField(blank=True, max_length=150)),
                ('activated_at', models.DateTimeField(null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app.importtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ImportTemplateUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_hash', models.CharField(max_length=64)),
                ('actor', models.CharField(max_length=150)),
                ('evidence', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='template_uses', to='app.importbatch')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uses', to='app.importtemplateversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='importtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='import_template_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='importtemplateuse',
            constraint=models.UniqueConstraint(fields=('batch', 'version', 'receipt_hash'), name='import_template_use_unique'),
        ),
    ]
