# Generated by Django 5.2.17 on 2026-10-06 14:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_import_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCollectionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('source_id', models.CharField(max_length=100)),
                ('context_hash', models.CharField(max_length=64)),
                ('manifest', models.JSONField()),
                ('manifest_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_collection_runs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCollectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_key', models.CharField(max_length=64)),
                ('version', models.PositiveIntegerField()),
                ('request_id', models.UUIDField()),
                ('request_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='app.devicecollectionrun')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('run', 'item_key', 'version'), name='collection_item_version_unique'), models.UniqueConstraint(fields=('run', 'item_key', 'request_id'), name='collection_item_request_unique')],
            },
        ),
    ]
