# Generated by Django 5.2.17 on 2026-10-06 15:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_device_collection_receipts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceTransformTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('current_version', models.PositiveIntegerField(default=0)),
                ('metadata_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_transform_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTransformVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(default='draft', max_length=20)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('lifecycle_hash', models.CharField(max_length=64)),
                ('activated_request_id', models.UUIDField(null=True, unique=True)),
                ('activated_request_hash', models.CharField(blank=True, max_length=64)),
                ('activated_by', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app.devicetransformtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceTransformReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('output_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derived_transforms', to='app.devicefile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_transform_receipts', to=settings.AUTH_USER_MODEL)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transforms', to='app.devicefile')),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='app.devicetransformversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='devicetransformtemplate',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='device_transform_owner_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='devicetransformversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='device_transform_version_unique'),
        ),
    ]
