# Generated by Django 5.2.17 on 2026-10-06 20:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_device_transform_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPCAnalysisView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('study_id', models.CharField(max_length=255)),
                ('definition', models.JSONField()),
                ('definition_hash', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spc_analysis_views', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spc_analysis_views', to='app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='SPCResultSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField(unique=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('note', models.TextField()),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='spc_result_snapshots', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='spc_result_snapshots', to='app.topic')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='app.spcanalysisview')),
            ],
        ),
        migrations.AddConstraint(
            model_name='spcanalysisview',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='spc_view_owner_code_unique'),
        ),
    ]
