# Generated by Django 5.2.17 on 2026-10-07 03:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_analysis_model_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_pages', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='page_definitions', to='app.topic')),
            ],
        ),
        migrations.CreateModel(
            name='TopicPageRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20)),
                ('request_hash', models.CharField(max_length=64)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_page_requests', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='app.topicpage')),
            ],
        ),
        migrations.CreateModel(
            name='TopicPageVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='app.topicpage')),
            ],
        ),
        migrations.AddConstraint(
            model_name='topicpage',
            constraint=models.UniqueConstraint(fields=('owner', 'code'), name='topic_page_owner_code_unique'),
        ),
        migrations.AddConstraint(
            model_name='topicpageversion',
            constraint=models.UniqueConstraint(fields=('page', 'number'), name='topic_page_version_unique'),
        ),
    ]
