# Generated by Django 5.2.17 on 2026-10-07 13:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_topic_page_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisModelChange',
            fields=[
                ('request_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('from_version', models.PositiveIntegerField()),
                ('to_version', models.PositiveIntegerField()),
                ('request_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analysis_model_changes', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='app.analysismodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('model', 'to_version'), name='model_change_version_unique')],
            },
        ),
    ]
