# Generated by Django 5.2.17 on 2026-10-07 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_analysis_model_change'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalWorkbench',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='personal_workbench', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('home_mode', models.CharField(default='overview', max_length=20)),
                ('home_entry', models.UUIDField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkbenchEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('target', models.CharField(max_length=80)),
                ('alias', models.CharField(blank=True, max_length=80)),
                ('section', models.CharField(blank=True, max_length=40)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.personalworkbench')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workbench', 'kind', 'target'), name='workbench_target_unique')],
            },
        ),
    ]
