"""Additional offline design sections. Content is catalog data, not live facts."""
from html import escape as h

def render_extra(d, table, section):
    f=d['framework']
    definition=table(['形态','定义','适用方式'],f['terms'])+'<h3>经营主指标、驱动与护栏</h3>'+table(['经营结果','主指标','驱动','护栏'],f['primary_kpis'])+'<p class="note">指标目标需依据真实历史和管理承诺制定，本方案不预设目标数值。</p><h3>设计、发布与运营</h3>'+table(['阶段','工作与交付'],f['design_lifecycle'])
    definition+='<h3>每个BI分析的定义模板</h3>'+table(['定义项','应写清什么','本厂成本专题示例'],f['analysis_definition_template'])+'<h3>汇总后派生指标示例</h3>'+table(['指标','业务公式','结果单位','解释边界'],f['derived_examples'])+'<p class="note">'+h(f['derived_status'])+'</p>'
    interaction=table(['交互','规则'],f['interaction_rules'])+'<h3>多品种、小批量的比较边界</h3>'+table(['边界','规则'],f['comparison_rules'])+'<h3>适合本厂的创新交互</h3>'+table(['设计','内容','价值','阶段'],f['innovations'])
    interaction+='<h3>数字变化时，先核对六类原因</h3><p>以下为呈现与复盘规则；各项按数据条件启用。不能把数据更正、口径变化或权限变化解释为经营改善。</p>'+table(['变化类型','核对什么','页面怎样呈现','例子与边界'],f['result_explanation'])
    pages=['<p>以下为可评审的布局蓝图，未填入经营数字，不表示功能已经全部实现。首期推荐 P02、P05、P06、P15。</p><label for="page-select">选择工作页 </label><select id="page-select">']
    pages.extend(f'<option value="{h(p["id"])}" {"selected" if p["id"]=="P02" else ""}>{h(p["id"]+" · "+p["name"])}</option>' for p in d['page_blueprints'])
    pages.append('</select>')
    for p in d['page_blueprints']:
        metrics=[next(m for m in d['metrics'] if m['id']==mid) for mid in p['metrics']]
        pages.append(f'<article class="blueprint" id="{h(p["id"])}"><small>{h(p["id"]+" · "+p["reader"])}</small><h3>{h(p["name"])}</h3><p class="question">{h(p["question"])}</p><div class="page-grid"><div class="wireframe"><small>布局示意 · 非经营数值</small><div class="wire-scope"><b>范围与数据时间</b><p>日期类型 / 截止点 · 配置 · 客户/组织 · 数据更新时间</p></div><div class="wire-metrics">'+''.join(f'<div><small>{h(c)}</small><strong>—</strong><small>期间 · 单位 · 口径 · 来源</small></div>' for c in p['cards'])+f'</div><div class="wire-explain"><b>解释差异</b><p>{h(p["visual"])}</p><small>点选维度保留上下文，显示可比条件与样本数</small></div><div class="wire-list"><b>定位业务对象</b><p>{h(p["detail"])}</p><div class="wire-columns"><span>对象 / 状态</span><span>差距 / 影响</span><span>责任 / 证据</span></div></div><div class="wire-action"><b>处理与复查</b><p>{h(p["decision"])}</p></div></div><aside><h4>下钻路径</h4><p>{h(p["drill"])}</p><h4>启用条件</h4><p>{h(p["gate"])}</p><h4>覆盖领域</h4><p>'+h(' · '.join(next(x['name'] for x in d['domains'] if x['code']==c) for c in p['domains']))+'</p><h4>关联指标</h4>'+''.join(f'<p><a href="#metric-{h(m["id"])}">{h(m["id"]+" · "+m["name"])}</a></p>' for m in metrics)+f'<small>{h(p["status"])}</small></aside></div></article>')
        spec=p['display_spec'];filters={x['id']:x['label'] for x in f['filter_library']}
        rows=[('候选筛选',' / '.join(filters[i] for i in spec['filters'])),('时间含义',spec['time_semantics']),('对象字段',' / '.join(spec['detail_columns'])),('默认排序',spec['default_sort']),('手机重点',spec['mobile']),('筛选边界',spec['filter_rule']),('权限边界',spec['privacy'])]
        display='<details><summary>本页的筛选、时间与交互定义</summary>'+table(['定义项','内容'],rows)+'<ol>'+''.join('<li>'+h(x)+'</li>' for x in spec['interaction'])+'</ol></details>'
        pages[-1]=pages[-1].replace('</article>',display+'</article>')
    mvp=f['mvp']
    phases=f'<div class="mvp"><h3>{h(mvp["title"])}</h3><p>{h(mvp["content"])}</p><p><b>验收：</b>{h(mvp["gate"])}</p><p><b>组织：</b>{h(mvp["people"])}</p><p><b>暂缓：</b>{h(mvp["defer"])}</p></div><h3>需求完整性检查</h3>'+table(['检查轴','覆盖范围'],d['coverage_audit'])
    phases+='<h3>按产品与业务条件启用的专项模块</h3><p>下面是10类条件性扩展，不假定本厂都生产或涉及；与完整候选需求目录配套裁剪，不能直接当作认证或合规结论。</p>'+table(['模块','适用条件','需覆盖的数据与问题','呈现'],f['conditional_modules'])
    basis=table(['依据','说明'],[['设计依据',d['design_basis']['context']],['适用边界',d['design_basis']['limits']],['参考链接核验',d['design_basis']['references']]])
    return section('terms','BI的不同形态与定义流程',definition),section('interaction','交互与创新设计',interaction),section('pages',f"{len(d['page_blueprints'])}个工作页布局蓝图",''.join(pages)),section('mvp','首期范围与完整性检查',phases),section('basis','设计依据与边界',basis)

EXTRA_STYLE='''
select{padding:10px;border:1px solid #cddbc5;border-radius:6px;font:inherit;max-width:100%;background:white;color:inherit}.blueprint{margin-top:28px;scroll-margin-top:90px}.blueprint h3{font-size:24px;margin:8px 0}.question{font-size:19px}.page-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(240px,1fr);gap:24px}.wireframe{background:#f1f6e9;border:1px solid #bed1b1;border-radius:10px;padding:20px}.wireframe small{font-size:11px;color:#617754}.wireframe p{font-size:13px;margin:8px 0}.wire-scope,.wire-explain,.wire-list,.wire-action{background:white;border:1px solid #d8e3ce;padding:17px;border-radius:7px;margin:14px 0}.wire-metrics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.wire-metrics>div{display:flex;flex-direction:column;background:white;padding:15px;border:1px solid #d8e3ce;border-radius:7px}.wire-metrics strong{font-size:28px;color:#397049}.wire-explain{min-height:140px;border-left:4px solid #709c62}.wire-columns{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid #dae4d3;margin-top:18px;padding-top:12px;font-size:11px}.wire-action{background:#e8f0dd;margin-bottom:0}aside{padding:18px;background:#f8faf3;border-radius:8px;font-size:13px}aside h4{font-size:13px;color:#5e7856}aside p{margin:6px 0 22px}.mvp{padding:24px;background:#eff5e6;border-radius:8px}.mvp h3{margin-top:0}.metric{scroll-margin-top:90px}.stats{display:flex;gap:30px;flex-wrap:wrap;margin:20px 0}.stats span{display:flex;gap:8px;align-items:baseline;font-size:13px}.stats b{font-size:30px;color:#276443}@media(max-width:900px){.page-grid{grid-template-columns:1fr}}@media(max-width:600px){.wire-metrics{grid-template-columns:1fr}.wireframe{padding:12px}nav{position:relative}.stats{gap:15px}.stats span{width:42%}}@media print{.page-grid{grid-template-columns:1.6fr 1fr}.blueprint{break-before:page}.wire-metrics{grid-template-columns:1fr 1fr}#page-select,label[for=page-select]{display:none}}
'''

EXTRA_SCRIPT='''
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
function showPage(id){const pages=qa('.blueprint'),target=pages.find(p=>p.id===id)||q('#P02');pages.forEach(p=>p.hidden=p!==target);q('#page-select').value=target.id}showPage('P02');q('#page-select').onchange=e=>{showPage(e.target.value);history.replaceState(null,'','#'+e.target.value)};
const metrics=qa('.metric');function filterMetrics(){const term=q('#metric-search').value.toLowerCase();metrics.forEach(m=>{m.hidden=!m.textContent.toLowerCase().includes(term);if(term&&!m.hidden)m.open=true});q('#metric-count').textContent=metrics.filter(m=>!m.hidden).length+' / '+metrics.length+' 项'}q('#metric-search').oninput=filterMetrics;filterMetrics();
function followHash(){const id=decodeURIComponent(location.hash.slice(1)),target=document.getElementById(id);if(!target)return;if(target.classList.contains('blueprint'))showPage(id);if(target.classList.contains('metric')){q('#metric-search').value='';filterMetrics();target.open=true}target.scrollIntoView()}window.addEventListener('hashchange',followHash);window.addEventListener('load',followHash);if(location.hash)followHash();
let visibilityBeforePrint=[];window.addEventListener('beforeprint',()=>{visibilityBeforePrint=qa('[hidden]').map(e=>[e,e.hidden]);visibilityBeforePrint.forEach(([e])=>e.hidden=false)});window.addEventListener('afterprint',()=>visibilityBeforePrint.forEach(([e,h])=>e.hidden=h));
'''
