import assert from 'node:assert/strict';
import {modelDiffMarkup,trialSideMarkup,impactMarkup,previewMarkup} from '../static/model_changes.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,n=0)=>Number(v).toFixed(n);
const table=(headers,rows)=>'<table><thead><tr>'+headers.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>`<td>${c}</td>`).join('')+'</tr>').join('')+'</tbody></table>';
const diff=[{path:'definition.filters',before:null,after:[{value:'00001<img src=x>'}],before_present:false,after_present:true}];
const summary={value:20,unit:'%',reason:'整范围独立重算',source_rows:10,valid_rows:10,missing_rows:0,numerator:2,denominator:10};
const side={ready:true,summary,display_label:'放行率 <script>x</script>',display_metric:'m0',grain:'一行一工单',date_label:'计划完工日',sample_note:'仅前15组',groups:2,truncated:false,dimension_label:'配置',sample_groups:[{dimension:'000019',m0:0},{dimension:'B',m0:null}]};
const impact={notice:'仅当前可访问资料',topics:[{name:'专题 <img src=x>',version:1,slots:[0,2]}],views:[{name:'我的视角',version:1,archived:true,scope_check:'日期角色变化'}],cards:[{code:'MC.000001',revision:1}],pages:[{code:'PG.000001',version:2,relation:'导航目标'}],snapshots:[{name:'历史快照'}]};
const data={before:{name:'原模型',version:1},candidate:{name:'候选 <svg>',version:2},notice:'这是配置预演',delta_note:'不推断经营改善',changes:diff,original_result:side,candidate_result:{...side,summary:{...summary,value:null,reason:'缺样本'}},population:{comparable:true,before:10,after:2,shared:2,added:0,removed:8,reason:'不是业务流失'},impact};
const frozen=JSON.stringify(data),html=previewMarkup(data,esc,num,table);
assert.equal(JSON.stringify(data),frozen);assert(!/<img|<script|<svg/.test(html));assert(!/undefined|NaN|\[object Object\]/.test(html));
assert(html.includes('000019')&&html.includes('00001')&&html.includes('0.0000'));assert(html.includes('分子 2.0000 / 分母 10.0000'));
assert(html.includes('未声明')&&html.includes('缺样本')&&html.includes('日期角色变化')&&html.includes('导航目标'));
assert(html.includes('保存模型 v2')&&html.includes('name="acknowledged" required')&&html.includes('minlength="5"'));
assert(html.includes('data-change-side="before" data-change-subset="removed"'));
assert(!html.includes('data-change-side="before" data-change-subset="added"'));
assert(trialSideMarkup({ready:false,error:'不支持客户 <img>'},'暂停',esc,num,table).includes('试算暂停'));
assert(impactMarkup({notice:'无可列依赖',topics:[],views:[],cards:[],pages:[],snapshots:[]},esc,table).includes('不代表没有其他使用者'));
assert(modelDiffMarkup([{...diff[0],before_present:true,after_present:false}],esc,table).includes('null'));
const cross=previewMarkup({...data,population:{comparable:false,reason:'跨数据集不配对'}},esc,num,table);
assert(!cross.includes('data-change-subset="shared"'));assert(cross.includes('跨数据集不配对'));
console.log(JSON.stringify({success:true,pure_js_markup:true,leading_zero_identity:true,zero_and_missing_separate:true,ratio_components:true,untrusted_text_escaped:true,explicit_acknowledgement:true,browser_acceptance:false,mobile_acceptance:false}));
